=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/CapturePaymentDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/CapturePaymentDetail",
  "definitions": {
    "CapturePaymentDetail": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "paymentStatus",
        "paymentEffectiveDate",
        "capturePaymentType",
        "id",
        "paymentType",
        "authorizationProcessingMode",
        "paymentNumber",
        "paymentAmount"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "name": {
          "type": "string"
        },
        "capturePaymentType": {
          "type": "string"
        },
        "handlingFeeAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentAuthorization": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isFinalCapture": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentStatus": {
          "type": "string"
        },
        "authorizationProcessingMode": {
          "type": "string"
        },
        "account": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "salesOrderPaymentSummary": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "latestGatewayResultCode": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name",
              "description"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            }
          }
        },
        "iPAddress": {
          "type": "string"
        },
        "commentText": {
          "type": "string"
        },
        "paymentNumber": {
          "type": "string"
        },
        "paymentGroup": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentAmount": {
          "type": "integer"
        },
        "latestGatewayInternalResult": {
          "type": "string"
        },
        "customerEmailAddress": {
          "type": "string"
        },
        "latestGatewayReferenceNumber": {
          "type": "string"
        },
        "paymentMethod": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "latestGatewayDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "balanceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentType": {
          "type": "string"
        },
        "paymentGateway": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "customerPhoneNumber": {
          "type": "string"
        },
        "latestPaymentGatewayMessageText": {
          "type": "string"
        },
        "paymentEffectiveDate": {
          "type": "string",
          "format": "date"
        },
        "paymentTreatment": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "externalCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "internalBusinessUnit": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentCancellationDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "macAddress": {
          "type": "string"
        },
        "totalAppliedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "netAppliedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalUnappliedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "latestGatewayInternalReferenceNumber": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/CapturePaymentDetailExample.json
{
  "paymentStatus": "exercitation",
  "paymentEffectiveDate": "1998-07-12",
  "capturePaymentType": "ipsum exercitation ea Excepteur",
  "id": "pariatur nulla sit",
  "paymentType": "eiusmod aute quis et nostrud",
  "authorizationProcessingMode": "dolor",
  "paymentNumber": "ex est in",
  "paymentAmount": 5732952,
  "balanceAmount": -26361189,
  "auditDetail": {
    "createdOn": "1971-12-05T02:47:33.123Z",
    "createdBy": "deserunt labore eiusmod Duis",
    "updatedOn": "1999-09-26T00:16:31.38Z",
    "updatedBy": "laboris Lorem",
    "isDeleted": true
  },
  "totalUnappliedAmount": -4088861,
  "paymentTreatment": [
    "in dolor Lorem anim",
    "amet velit consectetur sunt veniam",
    "officia Excepteur",
    "adipisicing incididunt amet consequat",
    "ut dolor nostrud nisi",
    "qui eiusmod id anim occaecat",
    "minim",
    "anim cupidatat eu nostrud",
    "et laboris tempor pariatur",
    "dolore cillum ea",
    "sint eiusmod",
    "est in",
    "Ut labore do",
    "eu sed tempor",
    "qui ut in magna sed",
    "laborum cupidatat irure",
    "ea cillum fugiat magna Ut",
    "ut",
    "fugiat",
    "laborum",
    "tempor adipisicing dolore occaecat mollit",
    "ad consectetur",
    "quis nulla officia",
    "exercitation mollit nulla culpa deserunt",
    "labore",
    "officia id enim",
    "Lorem",
    "sed quis anim labore",
    "anim",
    "sunt cupidatat aliquip ex",
    "proident aliquip officia",
    "consequat",
    "ad enim consequat ut aliquip",
    "in eu adipisicing"
  ],
  "commentText": "non dolor quis minim Duis",
  "latestGatewayResultCode": [
    {
      "id": "ipsum sint",
      "name": "minim quis",
      "description": "consequat sunt magna incididunt"
    },
    {
      "id": "Duis in aute consectetur Excepteur",
      "name": "sunt id non dolor",
      "description": "sunt"
    },
    {
      "id": "ullamco voluptate",
      "name": "ipsum in aliqua laborum incididunt",
      "description": "enim dolor sed tempor"
    },
    {
      "id": "cillum aute tempor fugiat nostrud",
      "name": "ut",
      "description": "elit est dolor ut et"
    },
    {
      "id": "in",
      "name": "occaecat aliquip ex",
      "description": "Excepteur officia tempor"
    },
    {
      "id": "velit",
      "name": "adipisicing in proident",
      "description": "laboris commodo occaecat"
    },
    {
      "id": "in in fugiat",
      "name": "sed",
      "description": "irure tempor consequat eu"
    },
    {
      "id": "dolor sint",
      "name": "Ut sed aliqua",
      "description": "ut officia dolor enim cillum"
    },
    {
      "id": "velit dolore et Lorem",
      "name": "elit sunt voluptate aute in",
      "description": "fugiat magna ullamco in"
    },
    {
      "id": "id occaecat anim",
      "name": "deserunt Excepteur nulla",
      "description": "ullamco"
    },
    {
      "id": "quis amet tempor esse commodo",
      "name": "reprehenderit irure",
      "description": "officia do magna culpa commodo"
    },
    {
      "id": "amet exercitation aliquip",
      "name": "ut ullamco",
      "description": "ad non sit culpa eu"
    },
    {
      "id": "ut ut qui",
      "name": "do irure officia",
      "description": "sunt sed laborum adipisicing"
    },
    {
      "id": "reprehenderit",
      "name": "sint aliqua magna cupidatat sed",
      "description": "irure aute"
    },
    {
      "id": "irure qui",
      "name": "minim deserunt Lorem",
      "description": "pariatur dolore qui"
    },
    {
      "id": "tempor labore exercitation ullamco laboris",
      "name": "commodo cupidatat velit dolore aute",
      "description": "laborum"
    },
    {
      "id": "laborum ullamco amet qui",
      "name": "Ut dolore laboris et sit",
      "description": "laboris"
    },
    {
      "id": "non velit magna officia",
      "name": "consequat",
      "description": "dolore adipisicing"
    },
    {
      "id": "deserunt irure commodo id",
      "name": "exercitation commodo",
      "description": "laboris"
    },
    {
      "id": "officia",
      "name": "aliqua ea",
      "description": "dolor anim sit dolore reprehenderit"
    },
    {
      "id": "Ut",
      "name": "sunt dolore nostrud consectetur",
      "description": "sed"
    },
    {
      "id": "laboris",
      "name": "consectetur pariatur quis",
      "description": "culpa deserunt pariatur commodo"
    },
    {
      "id": "deserunt cillum consectetur occaecat dolor",
      "name": "nulla dolore minim non Duis",
      "description": "dolore"
    },
    {
      "id": "voluptate incididunt",
      "name": "pariatur laborum",
      "description": "ex aliquip ullamco fugiat velit"
    },
    {
      "id": "Ut dolor",
      "name": "nostrud",
      "description": "tempor Excepteur mollit ea"
    },
    {
      "id": "nulla adipisicing",
      "name": "commodo veniam id amet in",
      "description": "consequat laborum in mollit Duis"
    },
    {
      "id": "dolore",
      "name": "culpa proident",
      "description": "quis"
    },
    {
      "id": "elit",
      "name": "laboris cillum sint nulla laborum",
      "description": "dolore"
    },
    {
      "id": "proident",
      "name": "et aliqua voluptate",
      "description": "deserunt et"
    },
    {
      "id": "ad eu",
      "name": "magna labore ex",
      "description": "laboris nulla voluptate commodo"
    },
    {
      "id": "adipisicing anim",
      "name": "laboris non",
      "description": "id"
    },
    {
      "id": "voluptate nulla mollit",
      "name": "et dolore id veniam",
      "description": "culpa officia exercitation dolor reprehenderit"
    },
    {
      "id": "minim consectetur sint incididunt",
      "name": "velit",
      "description": "consequat Lorem do"
    },
    {
      "id": "consectetur",
      "name": "ut nostrud veniam magna",
      "description": "aliquip labore dolor sunt Lorem"
    },
    {
      "id": "sit labore irure voluptate sed",
      "name": "do",
      "description": "voluptate minim eu commodo"
    },
    {
      "id": "velit",
      "name": "sit",
      "description": "in sint"
    },
    {
      "id": "magna sit pariatur occaecat",
      "name": "in sunt labore anim",
      "description": "dolor sint consequat"
    },
    {
      "id": "est",
      "name": "nisi ut irure culpa",
      "description": "minim et dolore eu sed"
    },
    {
      "id": "dolore in Duis sint",
      "name": "Duis adipisicing anim nulla ipsum",
      "description": "in ad quis occaecat"
    },
    {
      "id": "nostrud aute et",
      "name": "est velit",
      "description": "consectetur"
    },
    {
      "id": "aliquip nulla deserunt eu dolor",
      "name": "mollit Excepteur labore voluptate in",
      "description": "Duis do cillum dolor qui"
    },
    {
      "id": "ex do esse officia Duis",
      "name": "dolor",
      "description": "magna eu aute"
    },
    {
      "id": "aliquip",
      "name": "sed sit laborum",
      "description": "anim"
    },
    {
      "id": "et amet occaecat",
      "name": "aliquip consequat est",
      "description": "dolor ipsum mollit do minim"
    },
    {
      "id": "adipisicing cupidatat incididunt est pariatur",
      "name": "sit",
      "description": "quis cupidatat in nostrud irure"
    },
    {
      "id": "voluptate magna veniam",
      "name": "dolore",
      "description": "laboris in et minim"
    },
    {
      "id": "pariatur id ea",
      "name": "sunt",
      "description": "esse occaecat amet"
    },
    {
      "id": "exercitation ut nisi",
      "name": "sunt magna tempor enim dolore",
      "description": "dolor adipisicing aliqua"
    },
    {
      "id": "laboris",
      "name": "sint cupidatat aliquip nostrud",
      "description": "Ut"
    },
    {
      "id": "ad et",
      "name": "Ut",
      "description": "sint veniam Duis"
    },
    {
      "id": "ullamco amet sed Duis adipisicing",
      "name": "elit quis incididunt",
      "description": "sit Excepteur eiusmod"
    },
    {
      "id": "labore cillum aliqua qui Duis",
      "name": "proident nisi in minim ipsum",
      "description": "aliquip commodo dolore nisi adipisicing"
    },
    {
      "id": "reprehenderit eiusmod dolore aliqua",
      "name": "incididunt deserunt irure labore veniam",
      "description": "irure in"
    },
    {
      "id": "dolore tempor minim",
      "name": "tempor minim dolore",
      "description": "est commodo officia in sunt"
    },
    {
      "id": "consectetur ut nostrud dolore",
      "name": "qui reprehenderit in eiusmod consequat",
      "description": "dolore"
    },
    {
      "id": "deserunt pariatur proident esse voluptate",
      "name": "in ipsum nulla Ut eu",
      "description": "proident id ullamco"
    },
    {
      "id": "aute fugiat",
      "name": "sed dolor commodo deserunt quis",
      "description": "pariatur consequat nisi et"
    },
    {
      "id": "aute eu ea",
      "name": "dolor",
      "description": "elit aute magna"
    },
    {
      "id": "id mollit esse",
      "name": "sit aliquip aute anim",
      "description": "ut dolor"
    },
    {
      "id": "ut sunt esse proident",
      "name": "velit",
      "description": "laboris"
    },
    {
      "id": "Excepteur laboris ullamco Ut dolore",
      "name": "Excepteur velit Duis laboris in",
      "description": "dolore in cupidatat ut ut"
    },
    {
      "id": "do dolor anim",
      "name": "non aute eu",
      "description": "in voluptate et eiusmod"
    },
    {
      "id": "sunt non",
      "name": "commodo exercitation labore occaecat dolore",
      "description": "proident Duis"
    },
    {
      "id": "quis labore sint",
      "name": "quis exercitation aute",
      "description": "laboris reprehenderit commodo aute in"
    },
    {
      "id": "qui et amet est",
      "name": "culpa cupidatat consequat",
      "description": "culpa magna ad ullamco"
    },
    {
      "id": "ut nulla",
      "name": "amet in",
      "description": "id"
    },
    {
      "id": "non",
