=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/CompetitorDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/CompetitorDetail",
  "definitions": {
    "CompetitorDetail": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "competitorFromDate",
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "competitorStrengths": {
          "type": "string"
        },
        "competitorFromDate": {
          "type": "string",
          "format": "date"
        },
        "socialMediaPostRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitorThreats": {
          "type": "string"
        },
        "currentRatio": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "cashFlowGrowth": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitorObjectives": {
          "type": "string"
        },
        "netProfitMargin": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitorWeaknesses": {
          "type": "string"
        },
        "pressMentionsRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "assetTurnoverRatio": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitorToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitorLeverageOpportunities": {
          "type": "string"
        },
        "assetReturnRatio": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "ptoENumber": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "adKeywords": {
          "type": "string"
        },
        "adReachRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/CompetitorDetailExample.json
{
  "competitorFromDate": "1974-04-08",
  "id": "nisi Excepteur proident",
  "competitorObjectives": "reprehenderit quis Ut",
  "competitorToDate": "1982-12-13",
  "competitorWeaknesses": "laboris eu",
  "socialMediaPostRate": -81810054,
  "auditDetail": {
    "createdOn": "1952-07-02T08:51:07.305Z",
    "createdBy": "voluptate ea do",
    "updatedOn": "1947-07-12T15:48:22.078Z",
    "updatedBy": "quis labore occaecat elit",
    "isDeleted": true
  },
  "adReachRate": 98030473,
  "netProfitMargin": -71262342,
  "pressMentionsRate": -53965059,
  "ptoENumber": 65170518,
  "competitorStrengths": "tempor Excepteur velit",
  "assetTurnoverRatio": -31153242,
  "cashFlowGrowth": 53173359,
  "competitorThreats": "adipisicing aliquip esse eu non",
  "currentRatio": 43893370
}
