=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/CustomerDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/CustomerDetail",
  "definitions": {
    "CustomerDetail": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "customerStatus"
      ],
      "properties": {
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "customerStatus": {
          "type": "string"
        },
        "prospectRating": {
          "type": "string"
        },
        "netPromoterScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "customerSatisfactionScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "marketingEmailResponseRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalContractedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalProfitContributionAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "customerNumber": {
          "type": "string"
        },
        "churnScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "originatingCustomerSource": {
          "type": "string"
        },
        "totalLifeTimeValue": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalBookingsAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "last24MonthsNewRevenueAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "last12MonthsNewRevenueAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "last12MonthsSupportCallCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/CustomerDetailExample.json
{
  "id": "voluptate fugiat",
  "customerStatus": "irure elit fugiat",
  "marketingEmailResponseRate": 50705470,
  "totalContractedAmount": 8126281,
  "last24MonthsNewRevenueAmount": -93209387,
  "originatingCustomerSource": "commodo",
  "auditDetail": {
    "createdOn": "2005-04-27T08:55:55.744Z",
    "createdBy": "dolor in commodo eiusmod",
    "updatedOn": "1955-01-10T02:10:13.819Z",
    "updatedBy": "fugiat",
    "isDeleted": true
  },
  "last12MonthsNewRevenueAmount": 77273134
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/CustomerExample.json
{
  "id": "nostrud esse exercitation",
  "customerStatus": "irure",
  "totalContractedAmount": -92357243,
  "last12MonthsNewRevenueAmount": 77454523,
  "last12MonthsSupportCallCount": -25789889,
  "originatingCustomerSource": "aute officia ullamco",
  "prospectRating": "adipisicing magna",
  "marketingEmailResponseRate": 66675153,
  "netPromoterScore": -96018544,
  "last24MonthsNewRevenueAmount": 19544419,
  "party": [
    "tempor minim eu",
    "consequat officia est commodo",
    "labore",
    "cillum nostrud cupidatat",
    "deserunt",
    "consectetur irure tempor ad sed",
    "ullamco est consectetur tempor officia",
    "ipsum",
    "officia deserunt occaecat ex",
    "id sit mollit in",
    "voluptate ut",
    "dolor in in mollit",
    "irure ipsum ut deserunt",
    "quis officia in Lorem",
    "veniam consequat",
    "minim officia non commodo",
    "proident occaecat labore",
    "sunt incididunt quis consectetur eiusmod",
    "nisi laboris ut",
    "eu occaecat",
    "velit est deserunt fugiat consequat",
    "dolor",
    "quis dolore labore sit eu",
    "cupidatat ut consequat Duis",
    "fugiat et proident",
    "Excepteur",
    "labore Excepteur",
    "qui enim eiusmod",
    "reprehenderit quis occaecat"
  ],
  "totalProfitContributionAmount": -1037375
}
