=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/GoodsReceiptDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/GoodsReceiptDetail",
  "definitions": {
    "GoodsReceiptDetail": {
      "description": "Information about goods receipt",
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "id": {
          "description": "ID of the object in the source system",
          "type": "string",
          "example": "ID1244356"
        },
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "nativeId": {
          "description": "ID of the object in an other system",
          "type": "string",
          "example": "QWE244WAD00"
        },
        "number": {
          "description": "Natural number or name of the object",
          "type": "string",
          "example": "AAABBBCCC"
        },
        "lastModificationDateTime": {
          "description": "Timestamp of last modification from data in underlaying system",
          "type": "string",
          "example": "2021-01-21T21:21:21Z",
          "format": "date-time"
        },
        "goodsReceiptDate": {
          "description": "Date of goods receipt",
          "type": "string"
        },
        "postingDate": {
          "description": "Date of posting goods receipt",
          "type": "string"
        },
        "exported": {
          "type": "boolean",
          "description": "Information about export from system"
        },
        "items": {
          "type": "array",
          "description": "List of goods receipt items",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/GoodsReceiptDetailExample.json
{
  "id": "ea in enim Lorem",
  "lastModificationDateTime": "1955-06-07T22:51:24.624Z",
  "goodsReceiptDate": "Ut tempor minim",
  "nativeId": "ea incididunt sit",
  "exported": false,
  "auditDetail": {
    "createdOn": "1954-07-27T20:24:50.436Z",
    "createdBy": "pariatur",
    "updatedOn": "1999-10-26T10:49:00.605Z",
    "updatedBy": "dolore esse sed",
    "isDeleted": false
  },
  "items": [
    "aute occaecat qui nisi exercitation",
    "Ut culpa velit in reprehenderit"
  ],
  "number": "nisi est nulla irure",
  "postingDate": "proident incididunt aute sunt ad"
}
