=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/LeadDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/LeadDetail",
  "definitions": {
    "LeadDetail": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "leadSource"
      ],
      "properties": {
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "faxContactPhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "stateProvinceName": {
          "type": "string"
        },
        "leadStatus": {
          "type": "string"
        },
        "photoURL": {
          "type": "string"
        },
        "countryName": {
          "type": "string"
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "convertedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "description": {
          "type": "string"
        },
        "contactPointEmail": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "companyName": {
          "type": "string"
        },
        "streetName": {
          "type": "string"
        },
        "leadScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "mobileContactPhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "geoCodeLatitude": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "leadRating": {
          "type": "string"
        },
        "geoCodeLongitude": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "emailBouncedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "geoCodeAccuracy": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "leadSource": {
          "type": "string"
        },
        "convertedToAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "convertedToAccountContact": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "phoneContactPoint": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "lastActivityDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "annualRevenue": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "emailBouncedReason": {
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "isConverted": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "partnerAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/LeadDetailExample.json
{
  "id": "Ut eiusmod nisi nulla veniam",
  "leadSource": "consectetur",
  "emailBouncedDate": "00:01:01",
  "partyRole": [
    "sint",
    "enim fugiat labore pariatur",
    "culpa in",
    "velit laboris pariatur consectetur sed",
    "esse laborum",
    "aute do ut deserunt occaecat",
    "anim Excepteur pariatur adipisicing commodo",
    "ex Ut do",
    "sint nisi veniam",
    "aute commodo nisi",
    "ex amet Ut quis ea",
    "qui est ullamco",
    "dolor ea fugiat quis",
    "elit officia do est",
    "aute sint ipsum velit aliquip",
    "Lorem ut irure minim",
    "culpa voluptate et dolor Ut",
    "labore",
    "consectetur sit commodo occaecat aliqua",
    "aliqua ut minim nulla aliquip",
    "nulla laboris",
    "laboris quis est veniam",
    "voluptate in aliquip in",
    "adipisicing eu in",
    "ea minim consequat",
    "ad",
    "Duis mollit",
    "voluptate eiusmod sit",
    "commodo mollit",
    "in tempor reprehenderit ad anim",
    "elit commodo Ut amet",
    "consectetur",
    "ex officia proident",
    "et in",
    "quis tempor in veniam",
    "aute velit dolor dolor",
    "occaecat",
    "ea anim",
    "nulla esse commodo deserunt laboris",
    "cupidatat commodo",
    "ex in sunt",
    "occaecat fugiat nostrud",
    "aliquip",
    "Ut in dolore deserunt",
    "ut laboris ut mollit",
    "eu",
    "voluptate irure esse dolor",
    "labore tempor do ad",
    "voluptate do ex cillum",
    "ut",
    "in ullamco",
    "aute dolore labore sint velit",
    "ut officia adipisicing esse",
    "laboris",
    "nostrud commodo mollit eu",
    "ad sint",
    "cupidatat proident",
    "Lorem incididunt laborum nulla",
    "et Ut velit fugiat dolor",
    "culpa dolor deserunt eu labore",
    "ipsum mollit",
    "dolor id",
    "id in",
    "eiusmod tempor cupidatat mollit",
    "esse consequat",
    "cupidatat nostrud",
    "et aute esse aliquip irure"
  ],
  "geoCodeAccuracy": 76493367,
  "lastActivityDate": "2006-05-01",
  "geoCodeLongitude": -76669496,
  "auditDetail": {
    "createdOn": "1941-09-25T17:46:22.044Z",
    "createdBy": "minim pariatur cillum Excepteur",
    "updatedOn": "1969-10-29T05:32:02.466Z",
    "updatedBy": "labore minim est dolor",
    "isDeleted": false
  },
  "convertedToAccountContact": [
    "elit reprehenderit Duis sunt",
    "consectetur",
    "eu",
    "anim",
    "cupidatat adipisicing veniam",
    "eiusmod sunt veniam",
    "enim",
    "pariatur est in",
    "elit irure dolor consequat ad",
    "adipisicing sit",
    "ex esse cupidatat",
    "nulla",
    "sunt",
    "et ex amet in",
    "ullamco in amet magna tempor",
    "nostrud sunt in",
    "incididunt sed labore",
    "consectetur in",
    "est dolore laborum dolor veniam",
    "amet proident non",
    "nisi amet occaecat irure",
    "sint culpa amet quis occaecat",
    "aliqua nisi dolore",
    "consequat do",
    "non incididunt aliqua",
    "nulla",
    "sed labore",
    "fugiat qui",
    "aute irure nisi commodo Duis",
    "incididunt reprehenderit",
    "anim ipsum sed",
    "elit Ut magna",
    "officia consectetur fugiat sed anim",
    "ullamco labore esse culpa",
    "sunt cillum velit laborum",
    "Excepteur aliquip",
    "et anim",
    "sit fugiat amet ex nisi",
    "id consectetur sed elit ea",
    "ipsum dolor deserunt exercitation ad",
    "dolore aliquip",
    "enim in dolore",
    "nostrud magna qui",
    "fugiat aute",
    "aliquip ea deserunt ullamco irure",
    "dolore quis",
    "exercitation",
    "incididunt dolore",
    "minim",
    "in",
    "minim in anim",
    "ipsum",
    "voluptate",
    "eiusmod commodo",
    "culpa in consectetur magna",
    "cupidatat reprehenderit dolor",
    "irure commodo",
    "Ut in dolore enim ad",
    "voluptate sint dolor do",
    "commodo aliquip Ut sunt eiusmod",
    "commodo ex ut voluptate incididunt",
    "ut",
    "officia sed",
    "ut incididunt",
    "velit in officia id laborum",
    "pariatur ad",
    "veniam",
    "laboris irure",
    "est voluptate do sed aliquip",
    "Lorem reprehenderit anim esse",
    "anim",
    "eiusmod sed",
    "ut reprehenderit",
    "Lorem cupidatat et mollit",
    "ullamco aliqua ex",
    "enim incididunt",
    "id",
    "officia in est",
    "in",
    "occaecat labore in et eiusmod",
    "quis",
    "ea aute",
    "anim ea nostrud esse",
    "fugiat deserunt irure",
    "non aute magna",
    "in",
    "aute sed Ut quis",
    "fugiat dolore"
  ],
  "geoCodeLatitude": -27580596,
  "leadRating": "in dolore",
  "countryName": "Ut",
  "leadScore": -72813589,
  "contactAddress": [
    "qui reprehenderit aliquip labore",
    "sunt Ut",
    "mollit dolore labore ipsum",
    "reprehenderit ipsum",
    "ut officia veniam labore id",
    "voluptate exercitation",
    "velit occaecat",
    "deserunt consectetur anim",
    "sed in labore",
    "nisi laboris",
    "aliquip",
    "in",
    "deserunt non",
    "culpa",
    "aute eu sit est tempor",
    "elit cupidatat laborum",
    "deserunt",
    "anim in in",
    "dolor",
    "laboris dolore Excepteur sit",
    "amet exercitation commodo est",
    "culpa",
    "irure reprehenderit sed laboris et",
    "enim esse nulla mollit commodo",
    "in Lorem sint mollit pariatur",
    "officia non",
    "laboris in nostrud ut labore",
    "mollit commodo aliqua ut",
    "commodo",
    "veniam quis do",
    "cillum minim consectetur amet dolore",
    "do",
    "amet",
    "Lorem ullamco aliqua ut",
    "ut et Ut laborum ullamco",
    "tempor",
    "laborum voluptate ad",
    "ex eiusmod irure ipsum",
    "qui ullamco",
    "in in",
    "sint nostrud ullamco exercitation in",
    "non eu Duis ut aliquip",
    "magna elit",
    "ad mollit",
    "magna",
    "nisi in ea ut",
    "laboris ad Lorem",
    "ex quis",
    "reprehenderit",
    "qui eu",
    "commodo nulla aliqua qui",
    "Lorem id",
    "ea et",
    "culpa",
    "officia sunt quis esse",
    "et anim sit irure Ut",
    "ut Lorem",
    "ut",
    "proident",
    "irure laborum",
    "nisi reprehenderit",
    "consequat consectetur dolor eiusmod incididunt",
    "labore non sunt nisi sit",
    "in",
    "proident laboris",
    "ad reprehenderit fugiat Excepteur est",
    "culpa labore dolore dolor",
    "dolor sit est ad minim",
    "irure nostrud dolore",
    "laboris ullamco ut",
    "Ut elit non",
    "ipsum"
  ],
  "contactPointEmail": [
    "est",
    "consequat",
    "ullamco adipisicing et",
    "ullamco eu proident Excepteur Lorem",
    "dolor sed non velit id",
    "occaecat ipsum incididunt"
  ],
  "companyName": "nulla pariatur quis occaecat",
  "convertedDate": "2009-03-17",
  "website": "ipsum",
  "faxContactPhone": [
    "velit occaecat",
    "in laboris",
    "ea",
    "culpa",
    "enim consequat elit in magna",
    "sint proident",
    "amet",
    "proident nostrud enim Duis Ut",
    "in",
    "ea voluptate",
    "nisi incididunt tempor fugiat dolor",
    "in id nostrud culpa tempor",
    "dolor occaecat",
    "occaecat sed Excepteur nisi",
    "sunt qui dolore",
    "cupidatat enim pariatur non labore",
    "do officia sunt adipisicing",
    "sit minim do",
    "ullamco velit",
    "aliqua",
    "exercitation sint",
    "ut exercitation enim voluptate Ut",
    "ut laborum quis",
    "ad Ut ipsum proident labore",
    "cupidatat proident mollit magna",
    "ex tempor fugiat qui culpa",
    "sit do Duis Excepteur",
    "Lorem dolor minim",
    "aliqua sint in",
    "veniam culpa nulla sint",
    "ut aliqua eiusmod magna",
    "officia est aliquip",
    "amet aliquip",
    "ad occaecat ipsum",
    "non",
    "Excepteur nisi ex ut nostrud",
    "in",
    "sunt",
    "officia ea velit",
    "occaecat Lorem pariatur ex enim",
    "pariatur",
    "adipisicing Duis commodo",
    "mollit",
    "sit",
    "cillum tempor nostrud consectetur",
    "sit incididunt ea deserunt ut",
    "dolor laborum",
    "nisi",
    "in in quis",
    "tempor sunt ipsum sit",
    "commodo labore",
    "labore anim pariatur",
    "Duis esse amet",
    "ut cupidatat ut Excepteur pariatur",
    "cillum dolor mollit",
    "non",
    "consequat aliquip",
    "Lorem",
    "Duis sint cillum occaecat",
    "ad",
    "anim reprehenderit ex",
    "occaecat do eu aliqua",
    "enim ad incididunt",
    "ut",
    "cillum sint dolore nostrud",
    "exercitation consectetur enim in",
    "aliqua anim",
    "magna elit anim",
    "id",
    "esse",
    "dolor Excepteur dolore laborum proident",
    "Excepteur sint",
    "eiusmod non Duis dolor irure",
    "est aute consectetur et id",
    "officia fugiat dolore",
    "et dolor officia",
    "magna ad dolor amet",
    "in dolor ut laboris aute",
    "ut elit sunt",
    "commodo labore ea",
    "in consectetur qui officia",
    "ex ad aliqua culpa",
    "est incididunt deserunt dolor",
    "in nostrud reprehenderit adipisicing sunt"
  ],
  "description": "ad dolor Lorem",
  "photoURL": "consequat culpa anim esse et",
  "phoneContactPoint": [
    "velit proident eu",
    "consequat ex",
    "nulla",
    "consequat anim commodo dolore eu",
    "velit nulla id sit",
    "pariatur eu aute veniam",
    "aute Duis pariatur cillum",
    "dolore nulla exercitation magna in",
    "sed aliquip",
    "adipisicing culpa",
    "aute consectetur",
    "elit aute ad",
    "eiusmod ut sed est",
    "Excepteur",
    "qui exercitation",
    "in in",
    "laborum in",
    "ut deserunt ipsum consequat nisi",
    "dolor",
    "nostrud",
    "esse non laborum",
    "Lorem aliqua aliquip laborum",
    "magna deserunt aliquip et voluptate",
    "nostrud laborum in",
    "laboris culpa do",
    "dolor sint irure tempor",
    "do ex quis",
    "laborum ea officia velit Ut",
    "aliqua nisi eu",
    "Excepteur",
    "dolor",
    "aliquip nulla dolore officia dolor",
    "culpa eiusmod reprehenderit cillum",
    "nulla in",
    "mollit",
    "laborum",
    "minim sed ipsum culpa dolor",
    "dolor cupidatat Duis dolore ut",
    "ea dolore ad nisi exercitation",
    "Lorem do",
    "in qui velit",
    "non elit",
    "est amet",
