=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/RefundPaymentDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/RefundPaymentDetail",
  "definitions": {
    "RefundPaymentDetail": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "paymentStatus",
        "paymentEffectiveDate",
        "id",
        "paymentType",
        "authorizationProcessingMode",
        "paymentNumber",
        "paymentAmount"
      ],
      "properties": {
        "paymentStatus": {
          "type": "string"
        },
        "authorizationProcessingMode": {
          "type": "string"
        },
        "account": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "salesOrderPaymentSummary": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "latestGatewayResultCode": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name",
              "description"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            }
          }
        },
        "iPAddress": {
          "type": "string"
        },
        "commentText": {
          "type": "string"
        },
        "paymentNumber": {
          "type": "string"
        },
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "paymentGroup": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentAmount": {
          "type": "integer"
        },
        "latestGatewayInternalResult": {
          "type": "string"
        },
        "customerEmailAddress": {
          "type": "string"
        },
        "latestGatewayReferenceNumber": {
          "type": "string"
        },
        "paymentMethod": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "latestGatewayDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "balanceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentType": {
          "type": "string"
        },
        "paymentGateway": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "customerPhoneNumber": {
          "type": "string"
        },
        "latestPaymentGatewayMessageText": {
          "type": "string"
        },
        "paymentEffectiveDate": {
          "type": "string",
          "format": "date"
        },
        "paymentTreatment": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "internalBusinessUnit": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentCancellationDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "macAddress": {
          "type": "string"
        },
        "totalAppliedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "netAppliedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalUnappliedAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "latestGatewayInternalReferenceNumber": {
          "type": "string"
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "externalCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/PaymentDetailExample.json
{
  "paymentStatus": "tempor consequat qui aliquip",
  "paymentEffectiveDate": "1979-02-14",
  "paymentType": "et",
  "id": "voluptate",
  "authorizationProcessingMode": "proident",
  "paymentNumber": "deserunt cupidatat aute cillum aliqua",
  "paymentAmount": -92068194,
  "externalCreatedDate": "1996-12-07",
  "customerEmailAddress": "Excepteur fugiat",
  "paymentCancellationDate": "1955-03-02",
  "iPAddress": "consequat",
  "paymentGateway": [
    "deserunt proident elit in irure",
    "Ut et esse amet adipisicing",
    "aliquip cupidatat sit Lorem fugiat",
    "aliqua",
    "aliquip amet qui sit quis",
    "ex",
    "consequat esse adipisicing",
    "anim Excepteur commodo",
    "magna in nulla",
    "Lorem aliquip nisi",
    "quis",
    "Duis do dolore",
    "in fugiat aliqua cupidatat",
    "eu mollit in",
    "ipsum Duis exercitation Ut officia",
    "dolore nulla minim laborum",
    "in",
    "Duis ut ex",
    "cillum ullamco nulla",
    "ut eu anim",
    "eiusmod in do",
    "id consequat mollit",
    "culpa est laboris proident",
    "incididunt cupidatat",
    "laboris",
    "in",
    "incididunt occaecat veniam",
    "in reprehenderit",
    "dolore sint",
    "dolore aliqua",
    "aute ullamco",
    "exercitation Excepteur in nisi",
    "ipsum exercitation",
    "esse voluptate irure id proident",
    "occaecat minim sint esse id",
    "Excepteur Duis occaecat",
    "ut ex",
    "officia eiusmod",
    "adipisicing consectetur elit",
    "aliqua exercitation est",
    "nisi elit irure culpa esse",
    "magna aute quis",
    "dolore ut in",
    "sed",
    "cillum eiusmod",
    "cillum",
    "deserunt Excepteur",
    "magna aliqua exercitation amet",
    "reprehenderit",
    "laboris",
    "consectetur nisi",
    "cillum tempor magna laborum"
  ],
  "paymentTreatment": [
    "pariatur",
    "adipisicing anim",
    "proident",
    "sint laborum dolor",
    "ut amet laboris",
    "consectetur id quis ea in",
    "id",
    "culpa ipsum consectetur voluptate laboris",
    "ad elit",
    "eu id Duis aliquip"
  ],
  "auditDetail": {
    "createdOn": "2009-09-04T13:40:42.035Z",
    "createdBy": "Excepteur esse mollit in sit",
    "updatedOn": "1953-12-29T02:08:03.475Z",
    "updatedBy": "laborum eu Duis Ut nisi",
    "isDeleted": true
  },
  "balanceAmount": 99198172,
  "paymentGroup": [
    "officia dolor Excepteur dolore irure",
    "Ut tempor nisi laborum dolor",
    "ullamco",
    "cillum Ut aute",
    "tempor Excepteur veniam",
    "consequat",
    "sint deserunt et",
    "mollit",
    "aliquip mollit sed in laborum",
    "labore ut irure mollit",
    "minim sit",
    "sint sunt eu pariatur",
    "exercitation sit elit",
    "sed proident tempor aliqua nulla",
    "elit ullamco sunt in cupidatat",
    "aute",
    "ipsum amet tempor commodo dolore",
    "ipsum",
    "Ut consequat occaecat",
    "Ut dolore minim enim",
    "culpa Ut Excepteur in nostrud",
    "exercitation fugiat eu velit tempor",
    "ipsum velit voluptate consectetur",
    "qui dolore proident dolor irure",
    "laborum sint",
    "dolore ex Ut irure",
    "enim ut",
    "eu nostrud aute consequat deserunt",
    "dolore occaecat in Lorem",
    "sint ut anim",
    "exercitation",
    "fugiat deserunt culpa cupidatat laborum",
    "deserunt",
    "pariatur quis",
    "Excepteur laboris officia sint dolore",
    "veniam Lorem consequat incididunt sit",
    "consectetur exercitation nisi in",
    "esse labore pariatur reprehenderit",
    "tempor minim",
    "ipsum Excepteur reprehenderit",
    "culpa Ut aute",
    "sit sed officia Duis",
    "deserunt reprehenderit",
    "Duis Ut consectetur",
    "do id Duis eiusmod",
    "qui",
    "velit non",
    "aliqua",
    "velit enim",
    "ad",
    "nostrud",
    "culpa aliquip",
    "velit tempor do fugiat",
    "dolor",
    "reprehenderit",
    "pariatur laborum laboris deserunt exercitation",
    "consectetur minim ut",
    "adipisicing in",
    "ullamco sunt ea proident",
    "adipisicing",
    "anim Duis dolore",
    "sit cillum Lorem ad dolor",
    "ut proident sed occaecat Lorem",
    "incididunt laborum et dolore in",
    "adipisicing irure",
    "fugiat do consequat adipisicing culpa",
    "reprehenderit consectetur ex",
    "esse est",
    "minim nisi elit",
    "amet",
    "eu",
    "nisi consectetur",
    "occaecat eu",
    "dolore aute officia esse eu",
    "laboris occaecat qui magna",
    "commodo",
    "laboris in ex",
    "velit fugiat voluptate cillum adipisicing",
    "sint quis",
    "est dolore sunt",
    "amet magna laboris sit",
    "dolore laboris qui ut",
    "qui incididunt commodo irure non",
    "non Duis consectetur Ut",
    "laboris laborum occaecat Lorem",
    "veniam in cillum et ut",
    "anim amet",
    "laborum nulla laboris do magna",
    "dolore",
    "commodo",
    "ullamco",
    "non tempor",
    "Lorem eu",
    "est anim pariatur cupidatat exercitation",
    "irure nostrud ipsum"
  ],
  "paymentMethod": [
    "ad enim esse cillum",
    "anim",
    "aute id qui",
    "eu sit in",
    "Duis aliqua qui dolore",
    "exercitation",
    "sed tempor ex",
    "quis",
    "consectetur nulla exercitation voluptate",
    "ipsum nisi ad Lorem enim",
    "occaecat ex tempor quis Ut",
    "voluptate minim velit",
    "non",
    "sint id",
    "cupidatat non",
    "in velit consectetur Duis ad",
    "aliqua ut",
    "sunt minim laborum",
    "nisi",
    "Lorem fugiat cupidatat ad",
    "occaecat quis ut nisi adipisicing",
    "ut reprehenderit eu",
    "anim in",
    "nisi",
    "deserunt Lorem Excepteur culpa",
    "ullamco est",
    "sed",
    "minim ea",
    "eiusmod aute do reprehenderit culpa"
  ],
  "latestGatewayDate": "1969-09-17",
  "latestGatewayReferenceNumber": "irure sunt ad",
  "netAppliedAmount": -72862405,
  "name": "veniam ex ullamco",
  "latestGatewayInternalResult": "aute",
  "macAddress": "sunt consequat proident in",
  "latestPaymentGatewayMessageText": "do",
  "latestGatewayInternalReferenceNumber": "ut officia magna anim",
  "internalBusinessUnit": [
    "dolore Duis",
    "Duis",
    "sit ut laboris reprehenderit ullamco",
    "esse labore voluptate ex minim",
    "deserunt enim eu est irure",
    "consectetur ut eu",
    "minim adipisicing dolore",
    "aute qui proident",
    "consectetur non Excepteur",
    "ullamco amet enim est deserunt",
    "officia",
    "irure Excepteur",
    "Duis",
    "et proident sed nisi aliqua",
    "sint",
    "commodo ea sit",
    "esse",
    "esse in qui sit anim",
    "ullamco aute",
    "ea consectetur in",
    "magna",
    "ullamco in aliquip Excepteur sed",
    "elit cillum dolore exercitation minim",
    "ullamco",
    "quis",
    "magna dolor ad veniam exercitation",
    "fugiat Duis ex",
    "proident cillum exercitation qui consectetur",
    "occaecat id",
    "dolor ut ad minim culpa",
    "sunt sed",
    "sed",
    "quis aute elit labore",
    "amet cillum deserunt cupidatat proident",
    "exercitation Excepteur ut Duis",
    "laborum nostrud anim sed",
    "magna laboris in commodo ipsum",
    "et minim",
    "amet",
    "aliquip",
    "in nisi consectetur Duis est",
    "fugiat sed",
    "incididunt",
    "est nisi nulla",
    "anim Lorem",
    "dolor pariatur sit amet labore",
    "elit velit in dolore dolore",
    "commodo fugiat do nulla",
    "nulla qui ullamco in mollit",
    "quis",
    "minim dolore",
    "exercitation deserunt voluptate Lorem",
    "irure Ut",
    "veniam aliquip dolor ullamco",
    "ut in irure consectetur",
    "sint dolore elit labore",
    "cillum",
    "pariatur anim",
    "magna Lorem laboris pariatur quis",
    "culpa do",
    "ex aute commodo",
    "dolore nulla aliquip ut non",
    "magna Ut culpa",
    "commodo eiusmod",
    "anim",
    "mollit ea reprehenderit",
    "Excepteur ullamco elit aute laboris"
  ],
  "account": [
    "sint do esse",
    "aute occaecat",
    "nisi aliquip culpa",
    "Excepteur",
    "do sint labore sed ex",
    "ipsum ex sed pariatur",
    "Ut pariatur deserunt eu",
    "reprehenderit officia ut ex",
    "ad sint",
    "laboris officia qui occaecat dolore",
    "Duis laborum ea",
    "officia Excepteur et",
    "nulla eu",
    "consectetur laboris deserunt",
    "in ipsum elit aute",
    "mollit",
    "quis est",
    "est esse culpa irure",
    "irure esse elit",
    "veniam reprehenderit ipsum nostrud",
    "fugiat",
    "aute non anim ad",
    "proident elit aliqua consectetur sed",
    "Excepteur laboris",
    "labore mollit reprehenderit",
    "fugiat Lorem laborum",
    "velit et officia id Ut",
    "sed consequat eiusmod sint",
    "sit consequat ullamco Duis",
    "ut Excepteur ullamco",
    "labore",
    "sed exercitation magna sit",
    "Duis dolore sunt mollit amet",
    "sint aliquip consectetur",
    "commodo ullamco ad",
    "occaecat ad dolore",
    "ipsum cupidatat",
    "nisi id voluptate",
    "magna aute pariatur voluptate",
    "ullamco ipsum ea",
    "Lorem",
    "cillum aliquip Duis sit",
    "Duis",
    "cillum culpa eiusmod reprehenderit laborum",
    "non cillum elit",
    "in sint elit Lorem Ut",
    "irure magna sunt",
    "consequat consectetur in esse",
    "esse non",
    "et eu proident",
    "adipisicing irure in ut",
    "dolore ex in Lorem culpa",
    "ex",
    "cupidatat",
    "fugiat dolor dolore",
    "consequat voluptate",
    "commodo irure",
    "cillum elit quis",
    "deserunt Ut eiusmod do",
    "dolor mollit proident Duis cupidatat",
    "id dolor magna ut",
    "cupidatat consequat eu esse aliquip",
    "dolore veniam dolor",
    "Duis deserunt qui in officia",
    "elit ut anim dolor",
    "culpa do in nostrud fugiat",
    "magna occaecat Lorem ut",
    "labore dolore",
    "dolor deserunt non",
    "id",
    "eiusmod enim",
    "qui",
    "fugiat dolor in Duis",
    "Excepteur qui amet deserunt reprehenderit"
  ],
  "customerPhoneNumber": "ut cillum",
  "commentText": "culpa veniam",
  "salesOrderPaymentSummary": [
    "commodo ipsum",
    "cillum nostrud in laborum",
