=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/jsonSchemas/SalesOrderDetailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/SalesOrderDetail",
  "definitions": {
    "SalesOrderDetail": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "name",
        "requestedStartDate",
        "salesOrderStatus",
        "id",
        "orderNumber",
        "salesOrderConfirmationStatus",
        "salesOrderType",
        "confirmationRecipientEmailText",
        "description",
        "developerStatusCode"
      ],
      "properties": {
        "auditDetail": {
          "description": "Defines standard system audit fields available for most types",
          "example": {
            "createdOn": "2021-01-21T21:21:21Z",
            "createdBy": "0054x000002IpBlAAK",
            "updatedOn": "2021-01-21T21:21:21Z",
            "updatedBy": "0054x000002xBGGAA2",
            "isDeleted": false
          },
          "type": "object",
          "additionalProperties": true,
          "required": [
            "createdOn",
            "createdBy",
            "updatedOn",
            "updatedBy",
            "isDeleted"
          ],
          "properties": {
            "createdOn": {
              "type": "string",
              "format": "date-time"
            },
            "createdBy": {
              "type": "string"
            },
            "updatedOn": {
              "type": "string",
              "format": "date-time"
            },
            "updatedBy": {
              "type": "string"
            },
            "isDeleted": {
              "type": "boolean"
            }
          }
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "totalPendingBillingAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "checkoutDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "priceCalculationStatusMessageText": {
          "type": "string"
        },
        "confirmationRecipientEmailText": {
          "type": "string"
        },
        "orderEndDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "isTaxExempt": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalProductTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isAlerted": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isAnonymous": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "description": {
          "type": "string"
        },
        "activatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "billToEmail": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requestedStartDate": {
          "type": "string",
          "format": "date"
        },
        "companyAuthorizedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "orderInsuranceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isClosed": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "shipToEmail": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "totalDeliveryAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "salesOrderConfirmationStatus": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "salesOrderType": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "customerAuthorizedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalCancelledBillingAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalAdjustedDeliveryTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "paymentMethod": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "totalAdjustmentAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "salesOrderStatus": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "renewalUpliftRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalProductAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "renewalTerm": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "originalOrder": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "billToAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "totalAdjustmentTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isGiftOrder": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "promiseFulfillmentDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "filedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "iSOCulture": {
          "type": "string"
        },
        "userDeviceSession": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "purchaseOrderNumber": {
          "type": "string"
        },
        "totalDeliveryFeeAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDeliveryTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "orderNumber": {
          "type": "string"
        },
        "seller": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "billToAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "shipToAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "fulfilledDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "billToContact": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paidDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalBookingAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "adjustedProductTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "promiseDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "packedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "isHistoricalOnly": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "grandTotalAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isContracted": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "canBillNow": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "adjustedTotalProductAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "orderDiscount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "internalBusinessUnit": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "salesChannel": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "orderStartDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "cancelDateType": {
          "type": "string"
        },
        "isReductionOrder": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "salesOrderSystemStatus": {
          "type": "string"
        },
        "isSuspended": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "billToPhoneNumber": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "purchaseOrderDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "soldToCustomer": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "billingDayOfTheMonth": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "cancelDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "shipToContact": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "taxRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "developerStatusCode": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/SalesOrderDetailExample.json
{
  "name": "commodo sit deserunt laboris proident",
  "requestedStartDate": "2019-11-05",
  "salesOrderStatus": [
    {
      "id": "fugiat Duis ullamco",
      "name": "nisi dolor aliqua occaecat"
    },
    {
      "id": "culpa",
      "name": "reprehenderit non elit"
    },
    {
      "id": "anim reprehenderit velit deserunt",
      "name": "officia velit"
    },
    {
      "id": "nulla elit",
      "name": "Duis amet"
    },
    {
      "id": "fugiat ex aliqua tempor ut",
      "name": "ullamco commodo quis"
    },
    {
      "id": "consectetur adipisicing irure",
      "name": "nulla Excepteur mollit amet aliqua"
    },
    {
      "id": "Excepteur labore adipisicing",
      "name": "aute"
    },
    {
      "id": "dolore ut amet",
      "name": "proident velit do aute"
    },
    {
      "id": "do sunt incididunt",
      "name": "cillum non"
    },
    {
      "id": "anim elit Lorem",
      "name": "nostrud adipisicing cillum do"
    },
    {
      "id": "cupidatat",
      "name": "Excepteur dolor esse sunt"
    },
    {
      "id": "qui deserunt",
      "name": "Ut veniam ex in"
    },
    {
      "id": "incididunt",
      "name": "commodo aute proident"
    },
    {
      "id": "eiusmod tempor laborum enim in",
      "name": "exercitation quis proident"
    },
    {
      "id": "dolor Duis",
      "name": "aliquip anim ipsum cillum proident"
    },
    {
      "id": "in ut commodo anim sed",
      "name": "enim voluptate"
    },
    {
      "id": "quis ad",
      "name": "eu sed"
    },
    {
      "id": "aute do sed esse",
      "name": "aliquip ex laboris reprehenderit"
    },
    {
      "id": "aliquip ea",
      "name": "officia ullamco minim"
    },
    {
      "id": "minim",
      "name": "incididunt"
    },
    {
      "id": "dolore",
      "name": "non"
    },
    {
      "id": "exercitation Excepteur commodo",
      "name": "voluptate et"
    },
    {
      "id": "dolore",
      "name": "culpa sunt elit cupidatat"
    },
    {
      "id": "Excepteur anim ipsum",
      "name": "cupidatat sint adipisicing magna"
    },
    {
      "id": "Excepteur elit veniam consequat",
      "name": "sunt enim aliqua aute"
    },
    {
      "id": "dolore nostrud aliqua id nulla",
      "name": "ad eu in"
    },
    {
      "id": "consequat laborum reprehenderit",
      "name": "ipsum reprehenderit"
    },
    {
      "id": "deserunt aliqua",
      "name": "mollit pariatur ut aliquip sint"
    },
    {
      "id": "in Ut anim dolore quis",
      "name": "ea nisi eiusmod Lorem irure"
    },
    {
      "id": "anim nostrud",
      "name": "sunt reprehenderit"
    },
    {
      "id": "id",
      "name": "ad cillum occaecat"
    },
    {
      "id": "aliqua",
      "name": "reprehenderit ipsum"
    },
    {
      "id": "voluptate",
      "name": "irure nostrud ipsum"
    }
  ],
  "id": "anim deserunt",
  "orderNumber": "aliqua Duis est",
  "salesOrderConfirmationStatus": [
    {
      "id": "nulla cillum officia qui",
      "name": "do consectetur ad officia sit"
    },
    {
      "id": "dolore cillum laborum eiusmod",
      "name": "non minim proident esse"
    },
    {
      "id": "est eiusmod",
      "name": "dolor commodo cupidatat eu ipsum"
    },
    {
      "id": "enim ea aliquip minim irure",
      "name": "mollit cupidatat"
    },
    {
      "id": "fugiat",
      "name": "aute esse ut nulla officia"
    },
    {
      "id": "Excepteur",
      "name": "irure ut amet adipisicing"
    },
    {
      "id": "est",
      "name": "eu sit id esse veniam"
    },
    {
      "id": "Duis",
      "name": "eu"
    },
    {
      "id": "nostrud fugiat",
      "name": "adipisicing nisi proident"
    },
    {
      "id": "ut minim deserunt",
      "name": "fugiat"
    },
    {
      "id": "nulla mollit ex Ut qui",
      "name": "est Duis ullamco minim"
    },
    {
      "id": "Excepteur proident ipsum",
      "name": "occaecat ipsum exercitation"
    },
    {
      "id": "mollit",
      "name": "Excepteur fugiat aute dolore quis"
    },
    {
      "id": "nisi in",
      "name": "ut in ipsum"
    },
    {
      "id": "aliquip reprehenderit",
      "name": "laborum aute"
    },
    {
      "id": "pariatur dolor ex",
      "name": "eu nostrud elit nulla ea"
    },
    {
      "id": "voluptate deserunt",
      "name": "commodo in cillum id"
    },
    {
      "id": "ex deserunt elit aute anim",
      "name": "amet sed exercitation veniam Duis"
    },
    {
      "id": "qui",
      "name": "Lorem"
    },
    {
      "id": "reprehenderit magna mollit consequat quis",
      "name": "ut aliqua dolor adipisicing"
    },
    {
      "id": "voluptate tempor aliquip",
      "name": "incididunt Ut"
    },
    {
      "id": "veniam et ea sed",
      "name": "eu"
    },
    {
      "id": "culpa pariatur consequat veniam",
      "name": "ea elit ut Duis fugiat"
    },
    {
      "id": "consectetur aliquip nisi ea laborum",
      "name": "magna"
    },
    {
      "id": "laboris aute",
      "name": "id quis occaecat fugiat"
    },
    {
      "id": "elit non exercitation incididunt labore",
      "name": "ea ad labore"
    },
    {
      "id": "laboris",
      "name": "Ut"
    },
    {
      "id": "dolor",
      "name": "culpa"
    },
    {
      "id": "esse et",
      "name": "in laborum ut"
    },
    {
      "id": "tempor consectetur",
      "name": "qui culpa sed irure ut"
    },
    {
      "id": "sed occaecat in cillum",
      "name": "sint"
    },
    {
      "id": "Duis in culpa",
      "name": "incididunt qui velit"
    },
    {
      "id": "consequat laboris",
      "name": "in quis ipsum"
    },
    {
      "id": "Lorem quis eu",
      "name": "mollit enim amet"
    },
    {
      "id": "ea",
      "name": "amet"
    },
    {
      "id": "do irure labore ullamco",
      "name": "reprehenderit ea ut"
    },
    {
      "id": "enim",
      "name": "consectetur id"
    },
    {
      "id": "Duis cillum voluptate nulla",
      "name": "in commodo velit proident"
    },
    {
      "id": "deserunt quis veniam ipsum",
      "name": "velit dolore"
    },
    {
      "id": "ullamco minim",
      "name": "in exercitation in"
    },
    {
      "id": "anim ipsum adipisicing",
      "name": "velit dolore esse Duis aliquip"
    },
    {
      "id": "ullamco irure non enim",
      "name": "laboris ea laborum"
    },
    {
      "id": "eu",
      "name": "ea enim laborum occaecat aute"
    },
    {
      "id": "qui id eiusmod magna",
      "name": "et ut reprehenderit laborum commodo"
    },
    {
      "id": "do",
      "name": "ad mollit cillum"
    },
    {
      "id": "sed",
      "name": "in ullamco"
    },
    {
      "id": "aliquip",
      "name": "in officia nulla"
    },
    {
      "id": "consequat labore",
      "name": "culpa nostrud"
    },
    {
      "id": "ex",
      "name": "fugiat ex nostrud in occaecat"
    },
    {
      "id": "incididunt veniam Lorem",
      "name": "anim incididunt"
    },
    {
      "id": "velit fugiat est",
      "name": "ullamco reprehenderit irure in"
    },
    {
      "id": "minim",
      "name": "Duis tempor"
    },
    {
      "id": "anim in",
      "name": "adipisicing"
    },
    {
      "id": "non Ut",
      "name": "veniam ipsum sint sunt labore"
    },
    {
      "id": "veniam esse ea",
      "name": "ullamco Lorem id aliquip"
    },
    {
      "id": "tempor nisi ullamco cupidatat",
      "name": "Duis nulla Ut aliquip sed"
    },
    {
      "id": "sint sunt",
      "name": "in"
    },
    {
      "id": "ex qui",
      "name": "eiusmod occaecat et adipisicing"
    },
    {
      "id": "consectetur commodo sunt ut sed",
      "name": "sit Ut ut ullamco proident"
    },
    {
      "id": "quis sint",
      "name": "eiusmod"
    },
    {
      "id": "eu eiusmod",
      "name": "esse proident dolore officia"
    },
    {
      "id": "Excepteur Lorem dolore aute",
      "name": "voluptate id in"
    },
    {
      "id": "id exercitation",
      "name": "dolor"
    },
    {
      "id": "ipsum Lorem consectetur est nisi",
      "name": "reprehenderit"
    },
    {
      "id": "consectetur aliqua",
      "name": "ut magna fugiat cillum"
    },
    {
      "id": "reprehenderit",
      "name": "tempor aute"
    }
  ],
  "salesOrderType": [
    {
      "id": "Lorem anim",
      "name": "ullamco cillum qui dolore sunt"
    },
    {
      "id": "minim tempor officia",
      "name": "voluptate"
    },
    {
      "id": "ad Excepteur dolore voluptate amet",
      "name": "minim eu velit amet"
    },
    {
      "id": "aliquip",
      "name": "cupidatat nisi Excepteur"
    },
    {
      "id": "cillum commodo",
      "name": "in aliqua consequat"
    },
    {
      "id": "fugiat officia in",
      "name": "commodo"
    },
    {
      "id": "Ut",
      "name": "sint exercitation laboris est"
    },
    {
      "id": "Lorem deserunt",
      "name": "officia mollit proident"
    },
    {
      "id": "nulla",
      "name": "enim"
    },
    {
      "id": "labore pariatur ullamco",
      "name": "in"
    },
    {
      "id": "nulla deserunt ut culpa",
      "name": "laborum cillum fugiat"
    },
    {
      "id": "irure sunt",
      "name": "sit irure"
    },
    {
      "id": "laboris",
      "name": "ut"
    },
    {
      "id": "enim",
      "name": "in eiusmod cupidatat quis"
    },
    {
      "id": "culpa",
      "name": "ex aliqua quis veniam"
    },
    {
      "id": "proident id",
      "name": "dolore"
    },
    {
      "id": "mollit et in",
      "name": "proident tempor eiusmod culpa"
    },
    {
      "id": "dolore anim",
      "name": "sunt dolor irure"
    },
    {
      "id": "ipsum",
      "name": "do eu et quis proident"
    },
    {
      "id": "deserunt aute",
      "name": "et dolor anim pariatur quis"
    },
    {
      "id": "exercitation ut laborum est",
      "name": "id officia qui aliqua"
    },
    {
      "id": "ad et reprehenderit",
      "name": "laboris ex"
    },
    {
      "id": "proident est",
      "name": "ad elit commodo in aliquip"
    },
    {
