=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/AccountContactSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/AccountContact",
  "definitions": {
    "AccountContact": {
      "type": "object",
      "example": {
        "id": "labore in",
        "account": [
          "ex tempor",
          "do tempor"
        ],
        "individual": [
          "aute Excepteur voluptate ex Duis",
          "consequat ex"
        ],
        "departmentName": "et",
        "contactEmail": [
          "minim sint quis deserunt qui",
          "dolor do cillum ipsum sed"
        ],
        "mailingAddress": [
          "proident cillum ullamco sed",
          "qui"
        ],
        "assistantName": "in dolor esse",
        "faxPhone": [
          "est aliqua velit ullamco occaecat",
          "eu dolor nisi sed"
        ],
        "businessPhone": [
          "enim velit eiusmod Duis amet",
          "quis ut enim elit"
        ],
        "assistantPhone": "dolor sit ipsum dolore",
        "lastActivityDate": "2020-01-29",
        "indirectRelationAccountContact": [
          "deserunt",
          "ut ullamco culpa tempor sint"
        ],
        "title": "reprehenderit incididunt Excepteur aute",
        "mobilePhone": [
          "commodo tempor",
          "elit ut ad labore"
        ],
        "homePhone": [
          "elit",
          "anim"
        ],
        "contactNote": "qui in elit",
        "reportsToAccountContact": [
          "incididunt",
          "enim officia do cupidatat et"
        ],
        "otherContactAddress": [
          "exercitation magna",
          "reprehenderit"
        ]
      },
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "reportsToAccountContact": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "mailingAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "account": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "faxPhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "departmentName": {
          "type": "string"
        },
        "businessPhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactEmail": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "mobilePhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "assistantPhone": {
          "type": "string"
        },
        "indirectRelationAccountContact": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "title": {
          "type": "string"
        },
        "lastActivityDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "contactNote": {
          "type": "string"
        },
        "assistantName": {
          "type": "string"
        },
        "individual": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "otherContactAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "homePhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/AccountContactExample.json
{
  "id": "voluptate minim irure",
  "mobilePhone": [
    "est sit ipsum laboris",
    "dolor officia",
    "quis sed eiusmod in",
    "irure Ut quis ipsum nisi",
    "in aliquip",
    "esse sunt nisi deserunt dolore",
    "est esse labore dolore",
    "adipisicing occaecat dolore officia",
    "cupidatat amet",
    "reprehenderit",
    "enim aute",
    "elit",
    "ea consequat tempor irure Lorem",
    "eu labore tempor Ut",
    "consequat commodo cupidatat Duis pariatur",
    "nulla aute ad dolor consectetur",
    "dolor",
    "dolore adipisicing nisi",
    "in veniam est",
    "ea in deserunt irure",
    "eiusmod laboris occaecat ullamco",
    "exercitation sit aliqua anim id",
    "et",
    "anim",
    "nulla cupidatat",
    "et cillum do in dolore",
    "in consequat",
    "consectetur",
    "nulla",
    "et Ut occaecat id",
    "eu ea tempor proident",
    "esse minim aliquip quis",
    "elit",
    "adipisicing aliqua",
    "magna ipsum",
    "in ipsum veniam nisi",
    "Duis elit dolore dolor",
    "pariatur esse",
    "proident laborum dolor anim"
  ],
  "contactEmail": [
    "reprehenderit adipisicing",
    "irure ullamco nulla exercitation consequat",
    "tempor cupidatat quis",
    "minim consectetur incididunt laborum",
    "pariatur mollit non dolore Ut",
    "velit",
    "sunt incididunt non",
    "velit culpa",
    "aute do fugiat magna",
    "culpa nulla sint",
    "officia consectetur qui",
    "deserunt",
    "est in laboris",
    "tempor sit magna ea",
    "irure",
    "quis anim",
    "sint anim velit adipisicing",
    "Excepteur",
    "non dolor nulla",
    "ad quis eu Lorem",
    "consectetur",
    "dolore consequat minim aute velit",
    "sint nisi labore in",
    "irure non adipisicing veniam dolore",
    "Duis in id tempor anim",
    "pariatur laborum ea",
    "proident et Ut irure",
    "aute Ut voluptate ea",
    "non sit",
    "dolor in tempor",
    "sed dolor officia",
    "velit consectetur",
    "consequat sunt",
    "adipisicing minim labore",
    "consequat ut anim est eiusmod",
    "in",
    "magna velit commodo dolor occaecat",
    "aliqua",
    "magna laborum dolore sint",
    "in ut",
    "consectetur sint",
    "enim id",
    "esse enim",
    "Ut et sint adipisicing",
    "in laborum",
    "dolore mollit",
    "deserunt sed",
    "amet",
    "laboris proident ea sed irure",
    "Ut consectetur aliquip laboris",
    "consequat",
    "occaecat in fugiat minim",
    "dolor Lorem sint",
    "Lorem eiusmod esse",
    "ut id",
    "nulla reprehenderit esse",
    "veniam proident ut nulla",
    "ipsum ut dolor",
    "reprehenderit",
    "sit ex non",
    "cupidatat",
    "Excepteur Lorem",
    "ipsum officia pariatur in aliqua",
    "reprehenderit dolor",
    "amet sit minim Duis",
    "deserunt cupidatat ad voluptate",
    "tempor in sed incididunt ad",
    "cillum",
    "voluptate adipisicing dolore cillum",
    "ullamco Excepteur id eu",
    "ea Duis",
    "ad sint anim consectetur",
    "cillum ex",
    "quis laborum eu cupidatat",
    "veniam ad pariatur laborum",
    "id Ut cillum dolore",
    "laboris ut anim consectetur Ut",
    "quis sed",
    "eu",
    "fugiat cupidatat",
    "nisi exercitation",
    "elit do"
  ],
  "mailingAddress": [
    "dolor eiusmod"
  ],
  "faxPhone": [
    "velit aliqua Duis ad dolor",
    "consectetur labore fugiat pariatur cupidatat",
    "eiusmod",
    "in ut incididunt dolor voluptate",
    "aliquip voluptate commodo",
    "eiusmod ullamco aliquip veniam culpa",
    "in",
    "do",
    "dolore minim culpa eiusmod",
    "sit Excepteur nostrud cillum",
    "esse",
    "irure aute",
    "esse",
    "dolore",
    "aliquip tempor Lorem do",
    "fugiat",
    "aute qui Duis incididunt",
    "dolore",
    "ex in"
  ],
  "departmentName": "amet",
  "assistantPhone": "aute anim eu mollit",
  "lastActivityDate": "1980-10-18",
  "homePhone": [
    "veniam",
    "minim",
    "aliquip",
    "eu",
    "minim Excepteur consectetur sunt quis",
    "nulla do",
    "cupidatat esse aute adipisicing",
    "in",
    "nulla sunt officia Lorem incididunt",
    "ut proident laborum nostrud eu",
    "nisi non est",
    "magna",
    "non",
    "nisi cillum ad elit",
    "dolor",
    "Excepteur dolore veniam",
    "occaecat eiusmod ipsum aliquip quis",
    "in",
    "aute nisi laborum",
    "aute Lorem aliqua do exercitation",
    "ad aliqua dolore ut",
    "aliqua",
    "ut non aliquip dolor nostrud",
    "ex Excepteur dolore",
    "Excepteur in Ut ex quis",
    "laboris ut quis ex est",
    "tempor dolor in labore Duis",
    "enim laborum in",
    "aute quis incididunt proident dolore",
    "fugiat",
    "labore",
    "consectetur aute amet",
    "nostrud id",
    "ipsum enim Excepteur laborum in",
    "laborum pariatur",
    "exercitation",
    "commodo labore culpa cupidatat eiusmod",
    "voluptate sed",
    "in quis qui",
    "ad pariatur enim",
    "in occaecat",
    "et qui dolore ex",
    "Ut",
    "cupidatat Excepteur dolor cillum dolor",
    "incididunt",
    "commodo",
    "ex",
    "dolor deserunt adipisicing qui",
    "enim Lorem reprehenderit culpa",
    "veniam",
    "irure ipsum labore do",
    "incididunt",
    "fugiat",
    "dolor reprehenderit",
    "nisi irure incididunt in",
    "laboris dolore ipsum ut",
    "velit occaecat",
    "id",
    "id veniam aliqua consequat",
    "nisi Ut aliqua",
    "commodo enim dolor",
    "Duis",
    "incididunt Excepteur reprehenderit deserunt",
    "exercitation tempor et",
    "commodo enim tempor",
    "ullamco in voluptate",
    "Duis Ut nisi Excepteur consectetur",
    "do dolor magna veniam laboris",
    "sit",
    "officia",
    "consectetur aliquip",
    "sint anim Duis minim incididunt",
    "in",
    "dolore esse",
    "veniam nulla Ut ipsum",
    "Ut nulla ut aute do",
    "nostrud velit quis consectetur",
    "cupidatat",
    "ex do",
    "Lorem quis cillum",
    "laboris esse consectetur",
    "sunt",
    "mollit veniam adipisicing",
    "culpa",
    "aliqua do voluptate sint",
    "ex dolor incididunt exercitation",
    "sit",
    "est amet proident",
    "voluptate",
    "incididunt pariatur in sed velit",
    "culpa in consectetur reprehenderit ex"
  ],
  "reportsToAccountContact": [
    "aute",
    "ex ullamco",
    "esse",
    "commodo in dolor proident",
    "in in cillum",
    "ad occaecat incididunt do aliquip",
    "minim aliqua",
    "aliqua do id",
    "amet eiusmod nulla dolore",
    "eiusmod in sed enim",
    "incididunt eiusmod nisi amet",
    "in sed",
    "cillum sint",
    "labore incididunt consectetur",
    "officia Duis consectetur",
    "dolor in",
    "culpa sunt",
    "in proident exercitation consequat",
    "adipisicing sit ut incididunt",
    "aliquip et aliqua irure veniam",
    "in consectetur deserunt",
    "officia ad proident consectetur velit",
    "ex sit",
    "cillum dolore et",
    "in dolore sunt do proident",
    "in culpa ad ipsum aute",
    "velit Ut",
    "ipsum dolor voluptate pariatur anim",
    "ad Ut nisi magna dolor",
    "consequat in ad labore fugiat",
    "aliquip Excepteur culpa est",
    "in est laborum Lorem",
    "ea",
    "consequat dolore laboris",
    "incididunt aliquip voluptate qui",
    "irure laborum cillum Duis",
    "laborum dolor",
    "do sit",
    "veniam laboris fugiat",
    "esse laborum quis",
    "deserunt cillum velit",
    "qui",
    "sit reprehenderit deserunt ut",
    "culpa minim ipsum ea",
    "est",
    "ullamco ut est",
    "tempor culpa anim magna cupidatat",
    "cillum",
    "tempor esse id qui dolor",
    "eu ullamco adipisicing occaecat",
    "nostrud qui pariatur",
    "in nostrud irure occaecat dolore",
    "quis in",
    "enim aliquip",
    "ut magna sunt exercitation dolor"
  ],
  "indirectRelationAccountContact": [
    "quis",
    "ullamco nulla do",
    "dolor non",
    "sit id Excepteur",
    "fugiat ipsum velit incididunt",
    "enim",
    "enim minim labore incididunt",
    "proident",
    "veniam amet",
    "ut consequat esse anim",
    "pariatur",
    "eiusmod esse quis ullamco culpa",
    "fugiat exercitation",
    "Excepteur in ex Ut",
    "culpa",
    "ea nulla ipsum magna",
    "quis",
    "sunt",
    "non ut dolor reprehenderit eu",
    "enim eiusmod",
    "tempor Duis veniam",
    "ad",
    "velit culpa non",
    "cupidatat elit consectetur pariatur",
    "pariatur velit elit dolore commodo",
    "cillum sunt do aute",
    "nostrud ad do Lorem",
    "veniam aliquip anim",
    "ad nostrud",
    "incididunt",
    "qui ad in",
    "fugiat mollit",
    "fugiat laboris officia voluptate",
    "nostrud Lorem sint amet",
    "labore et",
    "in dolore",
    "ex",
    "tempor aliquip",
    "veniam ullamco",
    "laboris officia tempor fugiat dolor",
    "consectetur minim",
    "sit mollit",
    "pariatur amet laboris",
    "adipisicing",
    "eu consequat",
    "exercitation ea",
    "laboris",
    "laborum sint",
    "consequat",
    "nostrud esse"
  ],
  "contactNote": "non sit",
  "assistantName": "reprehenderit",
  "businessPhone": [
    "sint ut culpa ea veniam",
    "ex dolore reprehenderit nulla ad",
    "anim labore deserunt est esse",
    "labore eu commodo ut nisi",
    "commodo est dolor enim nisi",
    "eu aliqua",
    "id tempor",
    "incididunt minim fugiat pariatur anim",
    "voluptate laborum",
    "exercitation nulla",
    "eu",
    "in labore nisi sit",
    "nisi adipisicing Duis",
    "ullamco eiusmod in",
    "Duis ea adipisicing",
    "sint cupidatat quis voluptate aute",
    "ex",
    "velit consectetur nostrud",
    "eu consequat culpa mollit",
    "sit est veniam dolore Duis",
    "sint",
    "irure veniam ex",
    "id esse",
    "aliquip Duis et",
    "ullamco",
    "ex",
    "quis",
    "qui pariatur magna Duis exercitation",
    "magna culpa",
    "fugiat deserunt amet",
    "et nulla culpa id"
  ],
  "title": "do Excepteur adipisicing",
  "individual": [
    "enim reprehenderit cupidatat Lorem",
    "consectetur",
    "deserunt",
    "Duis commodo eu",
    "sit sunt",
