=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/ContactPointPhoneSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContactPointPhone",
  "definitions": {
    "ContactPointPhone": {
      "type": "object",
      "example": {
        "contactPointType": [
          {
            "id": "do",
            "name": "commodo qui eu irure exercitation",
            "optInPriority": -43391706
          }
        ],
        "formattedNationalPhoneNumber": "ex in",
        "id": "occaecat in Lorem tempor",
        "forBusinessUse": false,
        "party": [
          "ea in est"
        ],
        "forPersonalUse": true,
        "telephoneNumber": "sint velit",
        "activeFromDate": "1969-05-21",
        "shortCode": 40287489,
        "bestTimeToContactEndTime": "18:02:53",
        "isSMSCapable": true,
        "partyRole": [
          "sunt labore commodo veniam et"
        ],
        "isFaxCapable": false,
        "areaCode": "adipisicing consequat",
        "primaryFlag": true,
        "formattedInternationalPhoneNumber": "est Excepteur",
        "phoneCountryCode": "sit nulla pariatur",
        "countryName": "voluptate",
        "extensionNumber": "dolore adipisicing consequat",
        "formattedE164PhoneNumber": "dolore quis occaecat",
        "activeToDate": "1960-03-19",
        "bestTimeToContactStartTime": "10:06:39",
        "profileLastUpdatedDate": "23:18:20",
        "primaryPhoneType": "consectetur in cillum aliquip commodo",
        "profileOccurrenceCount": -90807568,
        "profileFirstCreatedDate": "21:33:06"
      },
      "additionalProperties": true,
      "required": [
        "contactPointType",
        "formattedNationalPhoneNumber",
        "id",
        "telephoneNumber",
        "activeFromDate"
      ],
      "properties": {
        "primaryFlag": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactStartTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileLastUpdatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileOccurrenceCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileFirstCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactEndTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactPointType": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              },
              "optInPriority": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            }
          }
        },
        "forBusinessUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "forPersonalUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "extensionNumber": {
          "type": "string"
        },
        "phoneCountryCode": {
          "type": "string"
        },
        "countryName": {
          "type": "string"
        },
        "areaCode": {
          "type": "string"
        },
        "isSMSCapable": {
          "type": "boolean"
        },
        "shortCode": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "formattedInternationalPhoneNumber": {
          "type": "string"
        },
        "primaryPhoneType": {
          "type": "string"
        },
        "isFaxCapable": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "formattedE164PhoneNumber": {
          "type": "string"
        },
        "formattedNationalPhoneNumber": {
          "type": "string"
        },
        "telephoneNumber": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/ContactPointPhoneExample.json
{
  "contactPointType": [
    {
      "id": "ea enim deserunt irure adipisicing",
      "name": "laboris"
    },
    {
      "id": "ullamco cupidatat mollit ex dolor",
      "name": "esse voluptate in",
      "optInPriority": 67390832
    },
    {
      "id": "exercitation dolor qui minim nostrud",
      "name": "reprehenderit in ipsum nulla"
    },
    {
      "id": "in ut fugiat pariatur",
      "name": "ut sed"
    },
    {
      "id": "sed veniam sunt id",
      "name": "in tempor aliqua dolor id"
    },
    {
      "id": "laborum cupidatat aliquip ex dolor",
      "name": "Duis",
      "optInPriority": -61943990
    },
    {
      "id": "irure magna consequat",
      "name": "dolor dolor eu elit",
      "optInPriority": -273487
    },
    {
      "id": "anim aliquip sit fugiat",
      "name": "amet minim sed cillum aute"
    },
    {
      "id": "reprehenderit ut dolor veniam dolore",
      "name": "dolor"
    },
    {
      "id": "fugiat",
      "name": "velit in do anim amet",
      "optInPriority": -99205123
    },
    {
      "id": "officia sed sint ad reprehenderit",
      "name": "officia tempor",
      "optInPriority": -58176308
    },
    {
      "id": "proident",
      "name": "ipsum",
      "optInPriority": -41761035
    },
    {
      "id": "exercitation dolore do magna ipsum",
      "name": "magna laboris dolor fugiat",
      "optInPriority": 70164831
    },
    {
      "id": "ea pariatur elit",
      "name": "qui nostrud amet"
    },
    {
      "id": "exercitation dolore deserunt dolore",
      "name": "ut",
      "optInPriority": -76634857
    },
    {
      "id": "sunt incididunt commodo",
      "name": "eiusmod esse ut"
    },
    {
      "id": "mollit velit aliqua",
      "name": "cillum in velit irure Excepteur",
      "optInPriority": -93934354
    },
    {
      "id": "et quis aute ad",
      "name": "elit sint quis ad dolor",
      "optInPriority": 45130596
    },
    {
      "id": "irure",
      "name": "adipisicing"
    },
    {
      "id": "velit",
      "name": "mollit anim sint veniam irure"
    },
    {
      "id": "Ut dolore ea dolor",
      "name": "nostrud dolor",
      "optInPriority": -68132032
    },
    {
      "id": "ad deserunt velit consequat aliquip",
      "name": "id"
    },
    {
      "id": "sunt",
      "name": "amet",
      "optInPriority": 15645884
    },
    {
      "id": "minim ad Ut qui tempor",
      "name": "cupidatat consequat dolor"
    },
    {
      "id": "ipsum deserunt adipisicing",
      "name": "eiusmod incididunt ex",
      "optInPriority": 95806394
    },
    {
      "id": "aliquip eu",
      "name": "nulla",
      "optInPriority": -1635547
    },
    {
      "id": "proident cupidatat ea consequat",
      "name": "minim"
    },
    {
      "id": "culpa eu laborum incididunt",
      "name": "aute laborum Excepteur laboris"
    },
    {
      "id": "est",
      "name": "Lorem"
    },
    {
      "id": "qui",
      "name": "dolor",
      "optInPriority": 10564083
    },
    {
      "id": "Ut qui elit reprehenderit aliqua",
      "name": "laboris anim veniam",
      "optInPriority": 13246520
    },
    {
      "id": "enim deserunt",
      "name": "pariatur",
      "optInPriority": 43980005
    },
    {
      "id": "cillum",
      "name": "enim",
      "optInPriority": -59255663
    },
    {
      "id": "reprehenderit et",
      "name": "ipsum mollit elit ea consectetur"
    },
    {
      "id": "Ut incididunt veniam tempor",
      "name": "dolor tempor ipsum"
    },
    {
      "id": "eiusmod",
      "name": "est elit adipisicing"
    },
    {
      "id": "exercitation velit nisi Excepteur",
      "name": "et"
    },
    {
      "id": "ad veniam",
      "name": "ad ipsum laboris enim pariatur"
    },
    {
      "id": "mollit elit deserunt eiusmod dolore",
      "name": "tempor est",
      "optInPriority": 90164792
    },
    {
      "id": "labore",
      "name": "quis ipsum consequat ad"
    },
    {
      "id": "aliqua ipsum",
      "name": "ad",
      "optInPriority": 48289702
    },
    {
      "id": "velit officia",
      "name": "eu sit qui exercitation mollit"
    },
    {
      "id": "laboris dolore",
      "name": "nisi mollit",
      "optInPriority": -93347546
    },
    {
      "id": "laboris incididunt in",
      "name": "deserunt"
    },
    {
      "id": "irure consectetur ex",
      "name": "cillum ullamco est"
    },
    {
      "id": "Excepteur nostrud voluptate",
      "name": "velit ad",
      "optInPriority": -19629314
    },
    {
      "id": "pariatur esse nostrud ad do",
      "name": "nulla"
    },
    {
      "id": "in laboris id",
      "name": "ex sint",
      "optInPriority": 98588834
    },
    {
      "id": "consectetur do anim",
      "name": "non ea labore elit",
      "optInPriority": -59359223
    },
    {
      "id": "adipisicing labore occaecat sint",
      "name": "in id dolor aliquip officia"
    },
    {
      "id": "fugiat irure amet",
      "name": "esse Ut",
      "optInPriority": 97450054
    },
    {
      "id": "reprehenderit ipsum do aliqua",
      "name": "eiusmod aute deserunt consectetur",
      "optInPriority": -99842015
    },
    {
      "id": "commodo anim cupidatat adipisicing aliqua",
      "name": "enim nulla"
    },
    {
      "id": "minim ad sed ex",
      "name": "ut tempor",
      "optInPriority": -93237318
    },
    {
      "id": "et",
      "name": "eu Duis mollit proident aute",
      "optInPriority": 72821699
    },
    {
      "id": "consectetur Excepteur in irure",
      "name": "eiusmod"
    },
    {
      "id": "enim et consectetur",
      "name": "tempor eu Ut nisi dolore",
      "optInPriority": 37501251
    },
    {
      "id": "in exercitation quis",
      "name": "aute dolore"
    },
    {
      "id": "quis cupidatat",
      "name": "cillum dolore eu"
    },
    {
      "id": "adipisicing laborum ut incididunt sunt",
      "name": "est nostrud sed"
    },
    {
      "id": "dolor",
      "name": "quis magna",
      "optInPriority": 34980759
    },
    {
      "id": "cillum nulla irure ullamco",
      "name": "sint deserunt elit"
    },
    {
      "id": "ipsum eiusmod fugiat pariatur",
      "name": "eiusmod Duis"
    },
    {
      "id": "reprehenderit labore Lorem et sed",
      "name": "ut adipisicing",
      "optInPriority": -18736977
    },
    {
      "id": "ut esse ipsum consequat voluptate",
      "name": "deserunt"
    },
    {
      "id": "laborum ad minim",
      "name": "proident irure"
    },
    {
      "id": "occaecat",
      "name": "veniam commodo nisi magna cupidatat",
      "optInPriority": 32547783
    },
    {
      "id": "id",
      "name": "fugiat deserunt sint",
      "optInPriority": 40981512
    },
    {
      "id": "eiusmod proident tempor incididunt",
      "name": "nostrud commodo nulla minim adipisicing",
      "optInPriority": -96246803
    },
    {
      "id": "et nisi Lorem cupidatat",
      "name": "ut pariatur"
    },
    {
      "id": "do nostrud ad laborum veniam",
      "name": "mollit aliqua eiusmod"
    },
    {
      "id": "in enim",
      "name": "in consequat",
      "optInPriority": -67668111
    },
    {
      "id": "velit proident cillum incididunt ipsum",
      "name": "quis aliquip occaecat",
      "optInPriority": -82083144
    },
    {
      "id": "quis id incididunt",
      "name": "Ut in Duis",
      "optInPriority": 62769443
    },
    {
      "id": "ea laboris officia",
      "name": "et",
      "optInPriority": -9992669
    },
    {
      "id": "occaecat est non veniam",
      "name": "deserunt incididunt anim",
      "optInPriority": 79320256
    },
    {
      "id": "irure",
      "name": "dolor cillum"
    },
    {
      "id": "velit",
      "name": "in elit voluptate eu sed",
      "optInPriority": -19814010
    },
    {
      "id": "mollit Lorem incididunt",
      "name": "est"
    },
    {
      "id": "voluptate ea esse",
      "name": "exercitation"
    },
    {
      "id": "et officia",
      "name": "aute",
      "optInPriority": -77602085
    },
    {
      "id": "ex laborum",
      "name": "labore",
      "optInPriority": -88398476
    },
    {
      "id": "veniam ea Lorem",
      "name": "Ut anim proident amet in"
    },
    {
      "id": "laboris et adipisicing pariatur ipsum",
      "name": "ut"
    }
  ],
  "formattedNationalPhoneNumber": "adipisicing non aliquip amet",
  "id": "Ut id exercitation esse",
  "telephoneNumber": "ut",
  "activeFromDate": "1946-05-29",
  "extensionNumber": "in exercitation laborum",
  "party": [
    "commodo consequat labore exercitation in",
    "commodo mollit cillum eiusmod consequat",
    "esse dolore eu est officia",
    "enim et proident",
    "in dolore veniam anim quis",
    "non et labore",
    "cupidatat in sed occaecat incididunt",
    "ut amet veniam irure",
    "elit ex mollit reprehenderit",
    "ut fugiat sint",
    "labore elit sunt",
    "quis nisi nulla dolor velit",
    "sed sint non",
    "proident Duis qui est elit",
    "fugiat ipsum minim labore est",
    "ipsum sit est incididunt labore"
  ],
  "activeToDate": "1977-11-12",
  "forBusinessUse": false,
  "primaryFlag": true,
  "bestTimeToContactEndTime": "00:01:01",
  "areaCode": "fugiat id nostrud dolor",
  "isSMSCapable": false,
  "profileOccurrenceCount": -3655631,
  "phoneCountryCode": "est"
}
