=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/CreditTenderSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/CreditTender",
  "definitions": {
    "CreditTender": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "paymentMethodStatus"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "account": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentMethodType": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentMethodStatus": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/CreditTenderExample.json
{
  "id": "aliqua sit ut",
  "paymentMethodStatus": "anim tempor culpa minim non",
  "paymentMethodType": [
    "in amet irure aliquip eiusmod",
    "dolor irure proident sit reprehenderit",
    "deserunt fugiat Lorem",
    "irure mollit cillum eiusmod pariatur",
    "sunt velit",
    "in",
    "consectetur in fugiat",
    "voluptate culpa reprehenderit quis ullamco",
    "mollit consectetur dolore",
    "Ut veniam",
    "amet nisi eu dolore",
    "adipisicing cillum amet",
    "magna eu",
    "aute aliqua minim consectetur",
    "et Lorem reprehenderit officia",
    "sunt",
    "laboris",
    "do",
    "dolore consectetur officia ex do",
    "enim",
    "labore ad",
    "sint dolor",
    "incididunt dolore commodo cupidatat",
    "aliqua non ut ipsum nulla",
    "ex dolor ipsum sed",
    "ut sit fugiat",
    "sed",
    "culpa est ipsum",
    "ad dolor sed consectetur Ut",
    "sunt dolore consectetur sed in",
    "Ut nisi minim",
    "veniam",
    "enim laboris Lorem nostrud",
    "dolor incididunt",
    "magna",
    "esse consectetur adipisicing sit dolore",
    "ea dolore",
    "in quis non",
    "labore occaecat magna Excepteur"
  ],
  "account": [
    "id",
    "officia deserunt ipsum ea",
    "mollit in ad velit",
    "elit voluptate ut laboris",
    "consectetur irure sed",
    "incididunt",
    "irure non nostrud exercitation amet",
    "laborum Ut veniam cupidatat in",
    "ut ut deserunt est velit",
    "adipisicing",
    "Ut proident eu",
    "minim",
    "ad minim ut ut velit",
    "proident magna",
    "aliquip in incididunt id cillum",
    "exercitation",
    "qui nulla quis",
    "in laborum",
    "in cupidatat",
    "exercitation",
    "cillum reprehenderit enim officia incididunt",
    "dolor",
    "laboris dolor in",
    "Lorem sed ut veniam ipsum",
    "labore culpa",
    "in reprehenderit officia non enim",
    "amet esse dolor do",
    "cillum dolor",
    "ullamco sunt",
    "reprehenderit sed",
    "tempor nulla irure Duis dolor",
    "et enim commodo dolor",
    "consequat pariatur in adipisicing",
    "do",
    "sit qui enim",
    "dolor irure commodo sed amet",
    "quis irure labore eiusmod velit",
    "non ex id",
    "ea in",
    "sed Excepteur consequat eiusmod magna",
    "nulla deserunt",
    "minim non",
    "nisi aute quis",
    "deserunt tempor culpa",
    "est ut",
    "tempor qui",
    "minim exercitation",
    "ullamco consectetur mollit",
    "Lorem velit aliquip magna",
    "ea consequat reprehenderit dolor",
    "ex magna aliqua in velit",
    "proident ullamco id",
    "Duis magna in aute",
    "exercitation nisi quis",
    "aute",
    "do occaecat ut",
    "dolore irure ullamco deserunt laboris"
  ]
}
