=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/IndividualSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Individual",
  "definitions": {
    "Individual": {
      "type": "object",
      "example": {
        "partyType": "eiusmod Ut id",
        "personName": "anim adipisicing",
        "id": "reprehenderit dolor",
        "netWorth": 77131731,
        "birthDate": "1942-12-02",
        "dependentCount": null,
        "isHighRiskHobby": false,
        "isGoodDriver": true,
        "webSiteURL": "ex ut consequat sint veniam",
        "secondLastName": "mollit Lorem reprehenderit ad",
        "consumerCreditScore": -10552145,
        "religion": "magna",
        "doNotMarketFromUpdateDate": "2019-04-11",
        "isTobaccoConsume": true,
        "deathDate": "2009-05-08",
        "globalParty": "aute consectetur ex",
        "mailingName": "proident laborum eu",
        "hasDrugAbuseHistory": null,
        "hasAlcoholAbuseHistory": false,
        "militaryService": "reprehenderit sed veniam",
        "yearlyIncome": 85098518,
        "weddingAnniversaryDate": "1990-07-02",
        "orderingName": "nisi deserunt cupidatat",
        "militaryStatus": "nulla veniam aliquip non eiusmod",
        "personHeight": null,
        "primaryHousehold": [
          "voluptate sunt minim"
        ],
        "mothersMaidenName": "do eu esse minim et",
        "minorCitationCount": 44710945,
        "officialName": "anim deserunt eiusmod proident non",
        "doNotTrackLocationUpdateDate": null,
        "isGoodStudent": true,
        "primaryHobby": "Excepteur sit eiusmod",
        "mainLifeStyleType": "ut Lorem laborum",
        "personHeightUnitOfMeasure": "velit",
        "residenceCaptureMethod": "quis nisi et",
        "birthPlace": "reprehenderit",
        "primaryAccount": [
          "adipisicing aute nostrud"
        ],
        "nameSuffix": "ad Ut",
        "shouldForget": false,
        "doNotProfileFromUpdateDate": "1963-01-09",
        "gender": "id",
        "doForgetMeFromUpdateDate": null,
        "mainDietaryHabitType": "dolor Duis nisi dolore",
        "sendIndividualData": null,
        "firstName": "dolor pariatur magna in exercitation",
        "mainPersonalValueType": "ex nostrud",
        "noMergeReason": "labore cillum eu",
        "hospitalizationsLast5YearsCount": -1601571,
        "occupation": "Ut elit consequat",
        "doExtractMyDataUpdateDate": "1961-06-16",
        "occupationType": "elit in Ut culpa",
        "lastName": "aute labore",
        "mainDisabilityType": "sint nulla elit sit",
        "doNotProcessReason": "exercitation occaecat Lorem laboris",
        "taxBracketRange": "ex in pariatur non occaecat",
        "middleName": "anim",
        "doNotTrackUpdateDate": "1948-02-27",
        "personWeightUnitOfMeasure": "non in adipisicing",
        "overAgeNumber": -33978317,
        "yearlyIncomeRange": "mollit ut exercitation in aute",
        "influencerRating": 65125139,
        "isAlcoholConsumer": false,
        "photoURL": "Excepteur",
        "personWeight": null,
        "residenceCountryName": "minim non eiusmod",
        "consumerCreditScoreProviderName": "sed magna cillum",
        "currentEmployerName": "Ut",
        "isHomeOwner": null,
        "employedSinceDate": null,
        "mainPersonalityType": "id",
        "isHighRiskOccupation": true,
        "majorCitationCount": 87572917,
        "doNotProcessFromUpdateDate": "2017-02-10",
        "childrenCount": -55530924,
        "maritalStatus": "in anim",
        "convictionsCount": null,
        "mainLifeAttitudeType": "sed minim officia",
        "preferredName": "elit Excepteur aliqua amet adipisicing",
        "surgeriesLast5YearsCount": 43027205,
        "highestEducationLevel": "fugiat et anim elit do",
        "isDrugConsumer": false,
        "salutation": "in",
        "personLifeStage": "minim",
        "deathPlace": "labore magna qui",
        "ethnicity": "sed in quis"
      },
      "additionalProperties": true,
      "required": [
        "partyType",
        "personName",
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "hasAlcoholAbuseHistory": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "highestEducationLevel": {
          "type": "string"
        },
        "personHeight": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "mailingName": {
          "type": "string"
        },
        "surgeriesLast5YearsCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "doNotTrackUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "weddingAnniversaryDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "minorCitationCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "mainDietaryHabitType": {
          "type": "string"
        },
        "personHeightUnitOfMeasure": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "personName": {
          "type": "string"
        },
        "photoURL": {
          "type": "string"
        },
        "isHighRiskHobby": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "doNotProcessFromUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "militaryService": {
          "type": "string"
        },
        "maritalStatus": {
          "type": "string"
        },
        "doNotMarketFromUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "shouldForget": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "mainDisabilityType": {
          "type": "string"
        },
        "consumerCreditScoreProviderName": {
          "type": "string"
        },
        "isTobaccoConsume": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "webSiteURL": {
          "type": "string"
        },
        "secondLastName": {
          "type": "string"
        },
        "primaryHousehold": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "orderingName": {
          "type": "string"
        },
        "hospitalizationsLast5YearsCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "dependentCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "convictionsCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isGoodDriver": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "primaryHobby": {
          "type": "string"
        },
        "mainPersonalValueType": {
          "type": "string"
        },
        "isAlcoholConsumer": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "taxBracketRange": {
          "type": "string"
        },
        "childrenCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isGoodStudent": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "mainLifeAttitudeType": {
          "type": "string"
        },
        "netWorth": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "personWeight": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "birthDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "religion": {
          "type": "string"
        },
        "sendIndividualData": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "deathDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "doExtractMyDataUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "birthPlace": {
          "type": "string"
        },
        "overAgeNumber": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "doForgetMeFromUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "personWeightUnitOfMeasure": {
          "type": "string"
        },
        "mainLifeStyleType": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "hasDrugAbuseHistory": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "salutation": {
          "type": "string"
        },
        "mothersMaidenName": {
          "type": "string"
        },
        "doNotTrackLocationUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "ethnicity": {
          "type": "string"
        },
        "mainPersonalityType": {
          "type": "string"
        },
        "employedSinceDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "officialName": {
          "type": "string"
        },
        "isHighRiskOccupation": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "residenceCaptureMethod": {
          "type": "string"
        },
        "doNotProfileFromUpdateDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "nameSuffix": {
          "type": "string"
        },
        "isDrugConsumer": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isHomeOwner": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "doNotProcessReason": {
          "type": "string"
        },
        "occupationType": {
          "type": "string"
        },
        "deathPlace": {
          "type": "string"
        },
        "influencerRating": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "militaryStatus": {
          "type": "string"
        },
        "consumerCreditScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "yearlyIncome": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "preferredName": {
          "type": "string"
        },
        "personLifeStage": {
          "type": "string"
        },
        "yearlyIncomeRange": {
          "type": "string"
        },
        "majorCitationCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "middleName": {
          "type": "string"
        },
        "residenceCountryName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "occupation": {
          "type": "string"
        },
        "currentEmployerName": {
          "type": "string"
        },
        "partyType": {
          "type": "string"
        },
        "globalParty": {
          "type": "string"
        },
        "noMergeReason": {
          "type": "string"
        },
        "primaryAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/IndividualExample.json
{
  "partyType": "dolor",
  "personName": "cillum ullamco",
  "id": "tempor aliqua consequat non",
  "isHighRiskOccupation": true,
  "middleName": "exercitation occaecat ea culpa",
  "secondLastName": "deserunt non sint",
  "minorCitationCount": 55963815,
  "lastName": "proident",
  "militaryStatus": "et consequat cupidatat in"
}
