=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/InternalBusinessUnitSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/InternalBusinessUnit",
  "definitions": {
    "InternalBusinessUnit": {
      "type": "object",
      "example": {
        "partyType": "voluptate amet",
        "name": "in ullamco sed do amet",
        "id": "id1",
        "businessUnitType": "consectetur",
        "parentInternalBusinessUnit": [
          "aliquip officia non consectetur dolore"
        ],
        "primaryAccount": [
          "fugiat sint labore Excepteur"
        ],
        "noMergeReason": "ut cillum",
        "globalParty": "velit commodo voluptate"
      },
      "additionalProperties": true,
      "required": [
        "partyType",
        "name",
        "id",
        "businessUnitType"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "businessUnitType": {
          "type": "string"
        },
        "parentInternalBusinessUnit": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "partyType": {
          "type": "string"
        },
        "globalParty": {
          "type": "string"
        },
        "noMergeReason": {
          "type": "string"
        },
        "primaryAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/InternalBusinessUnitExample.json
{
  "partyType": "velit esse",
  "name": "magna",
  "id": "in consectetur ut Lorem adipisicing",
  "businessUnitType": "sit cupidatat ut id",
  "noMergeReason": "ipsum",
  "primaryAccount": [
    "commodo",
    "magna",
    "dolore",
    "sit id",
    "ut aliqua",
    "amet in",
    "qui est deserunt",
    "elit ad",
    "commodo",
    "mollit occaecat cillum",
    "minim irure est ut cupidatat",
    "nisi",
    "aliquip laborum fugiat dolore commodo",
    "sit cupidatat",
    "voluptate dolore nostrud qui id",
    "culpa anim",
    "consectetur officia cupidatat ullamco ad",
    "sit nisi fugiat labore",
    "in est mollit Duis in",
    "aliquip non ipsum eu est",
    "cupidatat ullamco",
    "labore ut",
    "sit",
    "cupidatat incididunt",
    "non consequat veniam",
    "dolor",
    "cillum sint aliqua",
    "aliqua amet culpa in",
    "quis enim commodo irure",
    "nisi fugiat deserunt amet laborum",
    "non magna Duis voluptate incididunt",
    "exercitation",
    "reprehenderit dolore laborum exercitation",
    "in pariatur non",
    "irure",
    "reprehenderit ipsum",
    "pariatur officia ut ipsum",
    "eu esse",
    "elit veniam Ut amet velit",
    "est",
    "aliquip ea in occaecat ex",
    "anim sunt ullamco",
    "proident",
    "veniam pariatur id",
    "aute",
    "reprehenderit occaecat aute enim sit",
    "irure dolore id reprehenderit nisi",
    "veniam cupidatat dolore esse in",
    "deserunt aute sunt et anim",
    "elit Ut",
    "sed in",
    "consectetur",
    "culpa id nulla reprehenderit magna",
    "voluptate id proident nulla Ut",
    "enim esse laborum occaecat ut",
    "in dolor",
    "nostrud laboris in voluptate eiusmod",
    "veniam aliquip cillum",
    "do mollit sint tempor",
    "dolor",
    "anim sed ullamco minim",
    "laboris Duis",
    "Excepteur quis officia",
    "quis in",
    "amet dolor sint",
    "ut nostrud ipsum",
    "Duis consequat",
    "ut ipsum officia dolore",
    "nisi laboris",
    "incididunt tempor reprehenderit consequat non",
    "consectetur in",
    "laborum",
    "amet cillum dolore in",
    "commodo esse ut",
    "aliqua mollit do labore",
    "labore qui",
    "esse cillum ad quis"
  ],
  "parentInternalBusinessUnit": [
    "labore veniam nisi dolore",
    "deserunt",
    "aute ad magna velit est",
    "mollit incididunt aute",
    "anim dolor Ut dolore",
    "ullamco ut",
    "proident est dolore dolor",
    "labore sit voluptate sed nulla",
    "nisi fugiat laboris minim",
    "cupidatat reprehenderit culpa aliquip ex",
    "consequat minim Ut in quis",
    "veniam esse sunt proident",
    "sed qui anim",
    "nostrud laborum exercitation in labore",
    "eiusmod anim elit dolore",
    "sint",
    "sed non dolore",
    "do mollit Lorem sunt",
    "dolore ullamco Ut",
    "Duis enim",
    "laborum",
    "cupidatat anim ut proident",
    "laboris",
    "cupidatat ut incididunt in",
    "incididunt exercitation enim laborum",
    "in magna",
    "pariatur et deserunt do in",
    "sunt",
    "magna dolore id officia",
    "tempor in ex ut",
    "reprehenderit sed nulla consectetur adipisicing",
    "dolore deserunt",
    "laboris consectetur nisi esse ipsum",
    "labore cupidatat sit magna",
    "aliquip incididunt ad",
    "qui occaecat commodo voluptate aute",
    "dolore",
    "aliqua exercitation est cupidatat dolor",
    "ipsum enim",
    "ut",
    "sed ipsum sit nostrud adipisicing",
    "aliquip dolore",
    "culpa proident",
    "Ut anim ut",
    "enim nisi in nostrud",
    "cillum est sunt enim commodo",
    "sed ullamco cillum sint",
    "nisi adipisicing",
    "culpa in sint ex",
    "in qui culpa enim eu",
    "dolore",
    "sunt proident consectetur mollit",
    "nulla sint incididunt tempor commodo",
    "mollit dolore",
    "reprehenderit labore magna exercitation",
    "occaecat ad",
    "officia aliquip elit mollit ad",
    "esse",
    "incididunt id ipsum cupidatat ut",
    "magna elit sed ex proident",
    "cillum reprehenderit eiusmod labore est",
    "dolore",
    "fugiat cillum Ut nulla cupidatat",
    "veniam aute",
    "veniam dolore pariatur ullamco voluptate",
    "aliqua dolore amet est",
    "in fugiat",
    "sit do Ut incididunt veniam",
    "id laboris eu labore consequat",
    "sit Lorem",
    "quis tempor mollit",
    "nisi in id occaecat",
    "non proident et",
    "velit",
    "culpa consectetur occaecat elit adipisicing",
    "amet",
    "fugiat",
    "Duis",
    "labore mollit adipisicing occaecat",
    "aliqua reprehenderit non",
    "aliqua dolore Excepteur qui anim",
    "Excepteur irure ut Duis",
    "aliqua",
    "Duis dolore anim sunt",
    "magna",
    "veniam laboris minim deserunt",
    "elit in velit",
    "ut pariatur nisi incididunt",
    "velit officia fugiat ex",
    "nostrud eiusmod anim",
    "fugiat",
    "laboris consectetur fugiat non",
    "dolor fugiat",
    "sed",
    "nulla dolor ad ipsum"
  ],
  "globalParty": "enim consectetur aliquip incididunt Lorem"
}
