=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/PaymentCardSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentCard",
  "definitions": {
    "PaymentCard": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "paymentCardType",
        "name",
        "id",
        "cardHolderName",
        "paymentMethodStatus",
        "expirationYear",
        "expirationMonth",
        "numberLastDigits",
        "maskedNumber",
        "issueNumber",
        "cardToken"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "creditCardExpired": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "cardToken": {
          "type": "string"
        },
        "issueNumber": {
          "type": "string"
        },
        "billToCity": {
          "type": "string"
        },
        "maskedNumber": {
          "type": "string"
        },
        "companyName": {
          "type": "string"
        },
        "cardHolderName": {
          "type": "string"
        },
        "numberLastDigits": {
          "type": "string"
        },
        "paymentCardType": {
          "type": "string"
        },
        "derivedCardTypeCode": {
          "type": "string"
        },
        "billToFirstName": {
          "type": "string"
        },
        "billToStreet": {
          "type": "string"
        },
        "expirationYear": {
          "type": "string"
        },
        "billToStreet2": {
          "type": "string"
        },
        "expirationMonth": {
          "type": "string"
        },
        "billToLastName": {
          "type": "string"
        },
        "paymentMethodType": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "paymentMethodStatus": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/PaymentCardExample.json
{
  "paymentCardType": "consectetur",
  "name": "deserunt esse",
  "id": "qui non fugiat est",
  "cardHolderName": "nisi exercitation",
  "paymentMethodStatus": "ullamco nulla cupidatat tempor minim",
  "expirationYear": "Duis in deserunt aliquip",
  "expirationMonth": "pariatur cillum sint veniam ex",
  "numberLastDigits": "consequat sunt do sit",
  "maskedNumber": "dolore",
  "issueNumber": "voluptate sint quis dolore",
  "cardToken": "eu culpa",
  "companyName": "qui in in",
  "billToFirstName": "Ut deserunt tempor exercitation aute",
  "billToStreet2": "incididunt ad dolore",
  "billToStreet": "esse tempor consequat"
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/PaymentCardDetailExample.json
{
  "paymentCardType": "est",
  "name": "id sed",
  "id": "dolore ex",
  "cardHolderName": "sit tempor qui ad et",
  "paymentMethodStatus": "veniam ullamco",
  "expirationYear": "exercitation pariatur",
  "expirationMonth": "cupidatat nulla aliquip",
  "numberLastDigits": "qui sint id Excepteur",
  "maskedNumber": "cupidatat reprehenderit aute",
  "issueNumber": "culpa veniam exercitation",
  "cardToken": "aute et ad do exercitation"
}
