=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/PriceBookEntrySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PriceBookEntry",
  "definitions": {
    "PriceBookEntry": {
      "type": "object",
      "example": {
        "id": "id1",
        "useStandardPrice": false,
        "minRequiredOrderValue": -88763183,
        "product": [
          "ea dolore in minim",
          "ipsum sunt Ut enim nostrud"
        ],
        "isActive": true,
        "servicePeriodCount": 67745648,
        "unitListPrice": 39837857,
        "maxRequiredOrderValue": null,
        "minRequiredQuantity": 66079859
      },
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "minRequiredQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "unitListPrice": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "product": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "minRequiredOrderValue": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isActive": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "maxRequiredOrderValue": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "useStandardPrice": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "servicePeriodCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/PriceBookEntryDetailExample.json
{
  "id": "elit dolore velit consequat",
  "minRequiredOrderValue": 84855091,
  "product": [
    "amet ea sint culpa in",
    "Excepteur fugiat non",
    "fugiat commodo Duis esse",
    "labore",
    "Excepteur in",
    "sit eu tempor est minim",
    "dolor eu ut",
    "Lorem",
    "mollit",
    "dolore minim",
    "voluptate aliquip laborum aliqua laboris",
    "dolore tempor",
    "nisi cillum",
    "laboris ea",
    "ad irure",
    "culpa eiusmod in aute dolor",
    "veniam culpa nostrud consequat voluptate",
    "officia",
    "ad occaecat veniam",
    "nostrud cupidatat eu sed",
    "occaecat in est",
    "dolore qui",
    "sunt tempor",
    "in mollit sint",
    "incididunt reprehenderit eu",
    "in occaecat",
    "Duis Excepteur sunt Ut",
    "veniam ut",
    "id",
    "Lorem",
    "sed in",
    "minim",
    "pariatur ex",
    "qui exercitation",
    "tempor proident aute est dolore",
    "eiusmod do et mollit magna",
    "ex dolore in",
    "anim magna Lorem irure aute",
    "ex cupidatat ullamco velit quis",
    "ipsum et veniam enim velit",
    "veniam ipsum elit",
    "sed deserunt amet commodo",
    "sunt minim aliqua nulla",
    "dolor voluptate anim pariatur reprehenderit",
    "nulla fugiat dolore",
    "sed amet enim dolor",
    "officia ut",
    "culpa anim do aliquip deserunt",
    "culpa esse tempor ad",
    "fugiat deserunt aute",
    "ex",
    "sunt irure consectetur nostrud",
    "in dolore laborum",
    "tempor ipsum Duis labore",
    "eiusmod",
    "nostrud"
  ],
  "maxRequiredOrderValue": -84246929
}
