=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/ProductTranslationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductTranslation",
  "definitions": {
    "ProductTranslation": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "longDescription": {
          "type": "string"
        },
        "product": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/ProductTranslationDetailExample.json
{
  "name": "reprehenderit sed sit",
  "id": "laborum",
  "longDescription": "reprehenderit et Excepteur adipisicing id",
  "product": [
    "in dolore Duis",
    "nostrud",
    "ipsum qui nostrud",
    "quis magna ut sed in",
    "velit",
    "elit laborum nulla",
    "ullamco",
    "ipsum",
    "et",
    "esse magna dolor in",
    "aliquip non commodo adipisicing magna",
    "Duis tempor ut elit",
    "labore",
    "nulla eiusmod consectetur",
    "dolore cillum laborum minim exercitation",
    "non consequat voluptate",
    "dolor",
    "nulla",
    "nostrud pariatur anim",
    "consectetur",
    "dolor nulla laboris est qui",
    "irure dolore minim do quis",
    "aliquip culpa aute cupidatat",
    "enim veniam",
    "sit incididunt reprehenderit id deserunt",
    "incididunt",
    "elit aliquip fugiat do ipsum",
    "tempor cupidatat velit culpa sint",
    "sit",
    "reprehenderit nulla eu",
    "Lorem laborum",
    "sed do",
    "aute nulla",
    "amet sint culpa",
    "sed ea minim laboris",
    "dolore",
    "dolore non",
    "dolor tempor",
    "dolor laboris esse nulla",
    "nulla eu consectetur",
    "cupidatat aliqua sit labore",
    "irure Excepteur ut",
    "tempor enim dolore do culpa",
    "non in occaecat commodo irure",
    "dolor in ipsum deserunt",
    "adipisicing sunt in",
    "Excepteur sunt laboris",
    "ut Ut ex labore",
    "magna amet ad",
    "laboris cupidatat in sed",
    "deserunt ipsum",
    "non irure nisi",
    "eu nulla mollit aliqua",
    "ea",
    "laboris sunt consequat",
    "et laborum anim minim",
    "culpa Duis amet",
    "elit",
    "labore officia laboris adipisicing",
    "quis cillum in",
    "laborum esse in ut",
    "dolor exercitation ad mollit",
    "ullamco fugiat",
    "aliquip velit eu",
    "dolore",
    "Lorem ad",
    "minim officia nulla",
    "ut consequat aute",
    "veniam voluptate in sit consectetur",
    "dolore",
    "dolor qui",
    "pariatur exercitation",
    "culpa Excepteur fugiat qui dolore",
    "aliqua enim qui fugiat pariatur"
  ]
}
