=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/SalesChannelSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/SalesChannel",
  "definitions": {
    "SalesChannel": {
      "type": "object",
      "example": {
        "id": "qui minim sunt",
        "name": "veniam ex",
        "externalRecord": "enim nulla",
        "salesChannelType": [
          {
            "id": "Ut",
            "name": "adipisicing nisi"
          }
        ],
        "description": "irure cupidatat voluptate",
        "salesChannelNumber": "anim in"
      },
      "additionalProperties": true,
      "required": [
        "name",
        "salesChannelNumber",
        "id",
        "salesChannelType",
        "description"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "externalRecord": {
          "type": "string"
        },
        "salesChannelType": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "description": {
          "type": "string"
        },
        "salesChannelNumber": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/SalesChannelExample.json
{
  "name": "nisi",
  "salesChannelNumber": "consectetur ullamco in incididunt",
  "id": "culpa in proident in",
  "salesChannelType": [
    {
      "id": "Duis dolore",
      "name": "Lorem"
    },
    {
      "id": "est ipsum",
      "name": "minim proident in"
    },
    {
      "id": "ut et dolore deserunt",
      "name": "nisi"
    },
    {
      "id": "anim et commodo sint velit",
      "name": "culpa anim"
    },
    {
      "id": "in proident dolore Ut dolor",
      "name": "ea sint culpa proident"
    },
    {
      "id": "pariatur Excepteur reprehenderit",
      "name": "ut"
    },
    {
      "id": "magna ut dolore sunt",
      "name": "dolore et"
    },
    {
      "id": "occaecat non anim voluptate et",
      "name": "exercitation ipsum non amet minim"
    },
    {
      "id": "anim labore sunt",
      "name": "ullamco ut"
    },
    {
      "id": "ipsum id veniam irure nulla",
      "name": "in Ut reprehenderit dolor"
    },
    {
      "id": "ex in mollit eiusmod veniam",
      "name": "sint veniam sunt Duis tempor"
    },
    {
      "id": "pariatur",
      "name": "sit Lorem ex ut"
    },
    {
      "id": "tempor laboris",
      "name": "esse minim veniam"
    },
    {
      "id": "cupidatat",
      "name": "magna culpa voluptate dolor"
    },
    {
      "id": "sed incididunt occaecat ullamco cillum",
      "name": "irure eiusmod sit tempor Duis"
    },
    {
      "id": "et in consectetur laborum quis",
      "name": "laboris in irure dolor Lorem"
    },
    {
      "id": "ut reprehenderit velit amet sed",
      "name": "quis voluptate reprehenderit"
    },
    {
      "id": "ut exercitation",
      "name": "sed exercitation"
    },
    {
      "id": "veniam",
      "name": "in ullamco"
    },
    {
      "id": "magna aliqua consectetur et cupidatat",
      "name": "deserunt"
    },
    {
      "id": "amet",
      "name": "ullamco amet dolor"
    },
    {
      "id": "dolore sunt velit ut",
      "name": "commodo in nisi labore"
    },
    {
      "id": "est ipsum non Ut nulla",
      "name": "in cillum"
    },
    {
      "id": "deserunt velit ut qui",
      "name": "commodo sit"
    }
  ],
  "description": "veniam",
  "externalRecord": "amet"
}
