=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/SalesOrderProductSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/SalesOrderProduct",
  "definitions": {
    "SalesOrderProduct": {
      "type": "object",
      "example": {
        "id": "in voluptate",
        "totalPriceAmount": 93534322,
        "quantityOrderedUOM": "Duis qui elit cillum",
        "orderProductNumber": "quis Duis",
        "product": [
          "consequat mollit tempor"
        ],
        "description": "anim",
        "orderedQuantity": -96054515,
        "salesOrderProductStatus": [
          {
            "id": "ullamco dolore",
            "name": "Ut in labore"
          }
        ],
        "salesOrder": [
          "ullamco incididunt in ut"
        ],
        "priceBookEntry": [
          "voluptate cupidatat Excepteur"
        ],
        "listPriceQuantityUOM": "quis sunt",
        "lineAdjustmentSubTotalAmount": -25084455,
        "totalDistributedAdjustmentTaxAmount": -87373972,
        "salesOrderProductAdjustedTaxAmount": 45572218,
        "totalDistributedAdjustmentAmount": 75142118,
        "salesOrderDeliveryGroup": [
          "aliquip esse exercitation sunt consequat"
        ],
        "originalOrderProduct": [
          "mollit aliqua"
        ],
        "totalAdjustmentTaxAmount": 89452328,
        "subscriptionRenewalMonthQuantity": -36943117,
        "orderManualAdjustmentSubTotalAmount": 89920784,
        "unitPriceAmount": -43736679,
        "fulfilledQuantity": 98799524,
        "unitTaxAmount": 1965254,
        "salesOrderProductReason": [
          "exercitation elit veniam velit"
        ],
        "subscriptionTermUnit": [
          {
            "id": "ex tempor Duis",
            "name": "dolor",
            "pluralName": "cupidatat enim esse non"
          }
        ],
        "totalRecurringPriceAmount": 76301862,
        "totalUnitPriceAmount": -96674305,
        "isAutomaticallyRenewed": false,
        "giftOrderMessageText": "aute",
        "promisedDate": "2017-03-01",
        "totalListPriceAmount": 70890710,
        "totalProductTaxAmount": -63887007,
        "segmentIndexNumber": -49317937,
        "shippingTaxAmount": 36224334,
        "totalManualAdjustmentAmount": 37951324,
        "endDate": "1944-08-19",
        "recurringPriceAmount": -69559718,
        "shippingPhone": [
          "minim voluptate"
        ],
        "segmentIndex": 96653393,
        "isBundleRoot": true,
        "shippingAddress": [
          "Duis in"
        ],
        "shippingEmail": [
          "ex"
        ],
        "discountAmount": -70603424,
        "totalLineAmount": -41514171,
        "totalAdjustmentAmount": -56599385,
        "commentText": "tempor",
        "allocationPartitionName": "do officia dolor cillum ad",
        "giftRecipientTelephoneNumber": "commodo exercitation do",
        "discountPercent": 38275017,
        "totalTaxAmount": 18023825,
        "totalDistributedTaxAmount": -66263502,
        "requestedStartDate": "2014-08-20",
        "deliveryTaxAmount": -49435531,
        "cancelledQuantity": -90815200,
        "sellerAccount": [
          "cillum"
        ],
        "allocatedQuantity": -60087236,
        "subscriptionTermQuantity": -73829037,
        "isBonusProduct": true,
        "allocationGroupName": "enim magna est",
        "isGift": false,
        "provisioningDate": "2017-09-03",
        "listPriceTermUOM": [
          {
            "id": "veniam in dolore ex officia",
            "name": "qui officia dolor",
            "pluralName": "adipisicing ea"
          }
        ],
        "availableQuantity": 90076547,
        "requestedEndDate": "1994-04-30",
        "shippingCostAmount": 94856364,
        "adjustedDeliveryTaxAmount": -71274717,
        "orderAdjustmentSubTotalAmount": 93598358,
        "handlingCostAmount": -48783123,
        "listPriceAmount": 67635824,
        "totalLineAdjustmentAmount": 94976817
      },
      "additionalProperties": true,
      "required": [
        "quantityOrderedUOM",
        "salesOrderProductStatus",
        "orderProductNumber",
        "id",
        "totalPriceAmount",
        "orderedQuantity",
        "description"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalRecurringPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalLineAdjustmentAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalPriceAmount": {
          "type": "integer"
        },
        "provisioningDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "fulfilledQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalLineAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "promisedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "shippingPhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "recurringPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "endDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "giftOrderMessageText": {
          "type": "string"
        },
        "quantityOrderedUOM": {
          "type": "string"
        },
        "totalProductTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "salesOrderProductReason": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "lineAdjustmentSubTotalAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "commentText": {
          "type": "string"
        },
        "orderProductNumber": {
          "type": "string"
        },
        "product": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        },
        "orderedQuantity": {
          "type": "integer"
        },
        "salesOrderProductStatus": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "unitPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "requestedStartDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "subscriptionRenewalMonthQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "orderManualAdjustmentSubTotalAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "allocatedQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "allocationPartitionName": {
          "type": "string"
        },
        "salesOrder": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isGift": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "unitTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "deliveryTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isBonusProduct": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "salesOrderProductAdjustedTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalAdjustmentAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "shippingTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalListPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalAdjustmentTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "orderAdjustmentSubTotalAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "subscriptionTermQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDistributedAdjustmentTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalDistributedTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "adjustedDeliveryTaxAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "shippingAddress": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "listPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "priceBookEntry": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "segmentIndex": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "shippingCostAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "isBundleRoot": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "discountAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "cancelledQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "shippingEmail": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "subscriptionTermUnit": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name",
              "pluralName"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              },
              "pluralName": {
                "type": "string"
              }
            }
          }
        },
        "listPriceTermUOM": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "name",
              "pluralName"
            ],
            "properties": {
              "id": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "name": {
                "type": "string"
              },
              "pluralName": {
                "type": "string"
              }
            }
          }
        },
        "salesOrderDeliveryGroup": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "listPriceQuantityUOM": {
          "type": "string"
        },
        "totalDistributedAdjustmentAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "segmentIndexNumber": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "totalUnitPriceAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "originalOrderProduct": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "availableQuantity": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "requestedEndDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "allocationGroupName": {
          "type": "string"
        },
        "sellerAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "giftRecipientTelephoneNumber": {
          "type": "string"
        },
        "isAutomaticallyRenewed": {
          "type": "boolean"
        },
        "discountPercent": {
          "type": "integer"
        },
        "totalManualAdjustmentAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "handlingCostAmount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/SalesOrderProductDetailExample.json
{
  "quantityOrderedUOM": "consectetur exercitation esse pariatur cupidatat",
  "salesOrderProductStatus": [
    {
      "id": "ut",
      "name": "aliqua"
    },
    {
      "id": "commodo aliquip pariatur ex dolor",
      "name": "in culpa"
    },
    {
      "id": "aliquip sunt sint elit",
      "name": "elit nostrud"
    },
    {
      "id": "officia nostrud in eiusmod eu",
      "name": "magna"
    },
    {
      "id": "id Duis enim in in",
      "name": "labore"
    },
    {
      "id": "id do aliqua",
      "name": "aute id deserunt"
    },
    {
      "id": "aliqua ex elit ea",
      "name": "ipsum ad laboris quis"
    },
    {
      "id": "aliquip",
      "name": "non"
    }
  ],
  "orderProductNumber": "ad in irure anim",
  "id": "mollit aliqua veniam",
  "totalPriceAmount": 49413672,
  "orderedQuantity": -70059426,
  "description": "fugiat tempor eu",
  "totalDistributedAdjustmentAmount": 42703959,
  "allocationGroupName": "qui",
  "provisioningDate": "1979-11-20",
  "availableQuantity": 95773460,
  "endDate": "1991-10-19",
  "shippingEmail": [
    "in irure ex",
    "veniam",
    "Duis incididunt sint id",
    "ea proident in aliquip aute",
    "aute sunt ea",
    "in exercitation esse dolore anim",
    "cupidatat labore ut non esse",
    "consectetur officia laboris dolore",
    "est mollit aliquip sunt fugiat",
    "proident in",
    "exercitation amet et voluptate aliqua",
    "Duis dolor"
  ],
  "totalRecurringPriceAmount": -36164162,
  "promisedDate": "1967-02-26",
  "product": [
    "laborum anim commodo",
    "irure voluptate adipisicing mollit in",
    "ullamco Ut ea",
    "nulla",
    "ea cillum dolore nulla Lorem",
    "est consectetur Lorem",
    "ut deserunt incididunt",
    "Duis ipsum mollit sunt irure",
    "in",
    "culpa do",
    "Excepteur veniam",
    "veniam",
    "et ullamco est",
    "ullamco do",
    "irure adipisicing",
    "elit in laborum sunt aute",
    "dolor",
    "velit",
    "ea",
    "qui",
    "non consectetur cillum",
    "dolore",
    "ipsum quis sunt Lorem laborum",
    "qui ipsum minim Duis voluptate",
    "sit qui officia dolore",
    "commodo minim",
    "Duis dolore",
    "qui",
    "in sunt nulla",
    "ut veniam aliquip",
    "ipsum",
    "in Excepteur ut Lorem",
    "consequat voluptate",
    "Lorem",
    "in dolore",
    "laborum Lorem sit",
    "exercitation sit dolore",
    "mollit sunt nisi qui ut",
    "deserunt ex ut",
    "cillum",
    "irure ex",
    "nisi nostrud",
    "qui",
    "ullamco Ut dolore velit",
    "dolore dolore Excepteur deserunt nisi",
    "aliqua ullamco esse dolor",
    "minim adipisicing",
    "reprehenderit velit",
    "anim dolore",
    "ut ipsum non ullamco ut",
    "nisi",
    "mollit in exercitation",
    "exercitation sunt",
    "quis incididunt in laborum",
    "reprehenderit veniam",
    "eu in reprehenderit",
    "et ea irure do ullamco",
    "dolor aute minim fugiat ad",
    "proident",
    "consequat elit fugiat",
    "est",
    "cupidatat",
    "ut incididunt",
    "fugiat",
    "cillum laborum",
    "sunt ad",
    "laborum labore",
    "consectetur sint in pariatur Lorem",
    "dolor anim minim",
    "ea do veniam mollit esse",
    "in Ut qui eu",
    "proident aute",
    "esse Lorem do dolore cillum",
    "ipsum aliqua culpa aute aliquip",
    "veniam fugiat laboris dolore",
    "ipsum",
    "in ad aliquip voluptate est",
    "deserunt sed",
    "cillum tempor ex culpa",
    "fugiat in",
    "enim exercitation laborum",
    "qui veniam",
    "in",
    "dolore irure minim occaecat"
  ],
  "discountAmount": 71871371,
  "isBundleRoot": true,
  "giftRecipientTelephoneNumber": "labore in nulla",
  "discountPercent": 41825821,
  "originalOrderProduct": [
    "aliquip elit sint ut quis",
    "ut et Duis est",
    "in dolor dolore ex",
    "qui consectetur",
    "do officia aute culpa",
    "Ut ex dolor cillum sit",
    "fugiat",
    "tempor esse",
    "sint",
    "Ut",
    "deserunt dolore Duis",
    "dolor fugiat",
    "dolore nisi quis",
    "cupidatat",
    "deserunt elit ex est",
    "nisi",
    "dolore esse dolor anim non",
    "voluptate ut",
    "occaecat reprehenderit in",
    "nostrud laborum voluptate",
    "occaecat Excepteur exercitation dolor fugiat",
    "reprehenderit quis",
    "nulla ea anim do",
    "voluptate velit ipsum in do",
    "in",
    "tempor",
    "ullamco",
    "voluptate",
    "est sed enim et fugiat",
    "labore adipisicing nisi aliquip ex",
    "ullamco minim",
    "ea velit aliqua",
    "Excepteur quis nisi laboris",
    "Excepteur",
    "reprehenderit",
    "ut",
    "minim aliqua Duis officia",
    "quis Ut est non",
    "magna dolore cillum ex sit",
    "incididunt pariatur sed",
    "nisi est tempor Lorem",
    "ea Lorem officia",
    "ut id",
    "nostrud ut in culpa consequat",
    "labore voluptate",
    "aute sunt consequat nisi",
    "magna sit quis laboris culpa",
    "consectetur ea incididunt anim qui",
    "magna dolore non nisi est",
    "proident mollit",
    "aute",
    "Lorem Duis ut adipisicing amet",
    "in voluptate ut",
    "magna in",
    "minim laborum fugiat",
    "do ad",
    "irure anim et est",
    "exercitation anim qui",
    "aliqua id",
    "officia Duis reprehenderit",
    "culpa fugiat aliquip mollit",
    "proident quis elit est veniam",
    "adipisicing irure consequat nostrud",
    "incididunt esse est",
    "occaecat quis tempor",
    "ex dolor eu id ut",
    "dolor dolor amet in",
    "eiusmod sit ut anim",
    "irure sit esse in laboris",
    "in laborum pariatur non",
    "voluptate dolore est nisi in",
    "enim sed aliqua",
    "eu minim dolore occaecat elit",
    "laboris",
    "aute adipisicing occaecat",
    "dolor anim do quis commodo",
    "non",
    "reprehenderit ut voluptate",
    "sit",
    "dolore ipsum",
    "elit",
    "fugiat culpa in sint",
    "qui laborum esse minim",
    "sunt aliqua sint",
    "enim",
    "amet incididunt irure fugiat non",
    "est veniam magna enim"
  ],
  "isAutomaticallyRenewed": false,
  "totalLineAmount": 79010671,
  "isBonusProduct": false,
  "totalLineAdjustmentAmount": -67703808,
  "subscriptionTermQuantity": -72898391,
  "cancelledQuantity": -59845915,
  "totalManualAdjustmentAmount": 12471631,
  "salesOrderDeliveryGroup": [
    "proident in Lorem deserunt",
    "proident sed enim",
    "eu Excepteur",
    "nisi",
    "non reprehenderit proident",
    "elit laborum consectetur",
    "aliquip ipsum",
    "qui quis do aliquip veniam",
    "eu aute cupidatat eiusmod in",
    "dolore ex irure consequat eu",
    "irure in",
    "in anim qui",
    "cillum tempor sint esse ullamco",
    "fugiat",
    "amet",
    "in in Lorem ea commodo",
    "esse enim sunt",
    "pariatur ad Excepteur et",
    "cillum",
    "aliquip voluptate",
    "Ut",
    "in sunt",
    "cupidatat",
    "sunt",
    "adipisicing et",
    "aliqua cillum",
    "sint in",
    "tempor",
    "reprehenderit fugiat",
    "deserunt velit ea dolore reprehenderit",
    "ut ea",
    "aliquip",
    "consequat",
    "dolore eu esse",
    "tempor ex",
    "qui",
    "exercitation",
    "enim",
    "sed",
    "eiusmod",
    "voluptate",
    "ullamco dolore",
    "ullamco sunt amet culpa",
    "dolore Ut sunt commodo labore",
    "aute dolor non enim anim",
    "ipsum veniam non",
    "dolor aliquip in ipsum",
    "deserunt commodo ullamco veniam exercitation",
    "commodo nostrud",
    "elit Ut officia eu veniam",
    "officia aliquip in",
    "proident officia pariatur",
    "laboris",
    "dolore id dolor aliqua",
    "elit anim occaecat laborum veniam",
    "officia voluptate adipisicing irure sit",
    "dolor",
    "incididunt in labore Lorem laborum",
    "incididunt",
    "sint aute Ut minim veniam",
    "labore et in Excepteur",
    "reprehenderit",
    "ex enim",
    "commodo",
    "elit Lorem aute",
    "et",
    "proident nisi quis labore sint",
    "est sed dolore",
    "consectetur qui in cillum",
    "cupidatat Duis adipisicing exercitation",
    "qui elit eu laborum ullamco",
    "qui",
    "reprehenderit in aliqua esse",
    "officia cupidatat enim nostrud",
    "in ut",
    "Ut ipsum incididunt",
    "ea Excepteur culpa",
    "nisi",
    "in quis amet",
    "adipisicing consectetur",
    "occaecat culpa fugiat enim",
    "quis laboris ex est dolore",
    "veniam commodo dolore culpa dolor",
    "dolor aute Ut do deserunt",
    "adipisicing ipsum",
    "deserunt aute non",
    "culpa",
    "ex eu fugiat sint cillum",
    "laborum",
    "aliquip",
    "tempor elit",
    "quis eiusmod Excepteur",
    "eiusmod quis sit deserunt",
    "enim ullamco voluptate aliqua",
    "incididunt irure",
    "sint"
  ]
}
