=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/SupplierSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Supplier",
  "definitions": {
    "Supplier": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "activeFromDate"
      ],
      "properties": {
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "satisfactionEthicsRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractInvoiceAccuracyRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "satisfactionWeightPercent": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractOnTimeDeliveryRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitiveWarrantyRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitiveMarketingRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractDeliveryCorrectnessRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitiveWeightScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractSLAIssueRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitiveWeightPercent": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "supplierScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitiveProductPriceRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractWeightPercent": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "supplierSpend": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "satisfactionTechnicalSupportRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractWeightScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "satisfactionCustomerServiceRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "satisfactionWeightScore": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractSourcingCycleDays": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "supplierType": {
          "type": "string"
        },
        "isCarrier": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractProductReturnRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "competitiveCostAvoidanceRank": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractProductQualityRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contractBudgetCostRate": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/SupplierExample.json
{
  "id": "elit exercitation sunt",
  "activeFromDate": "1979-06-08",
  "satisfactionTechnicalSupportRank": 56416659,
  "supplierScore": 87879518,
  "satisfactionWeightScore": -4463729,
  "isCarrier": true,
  "contractProductQualityRate": 75959582,
  "satisfactionCustomerServiceRank": 85870386,
  "contractDeliveryCorrectnessRate": 4272025,
  "contractSourcingCycleDays": -81217752,
  "contractWeightScore": 40961385,
  "competitiveWeightScore": -59751722,
  "competitiveProductPriceRank": -97107508,
  "contractOnTimeDeliveryRate": 11291062
}
