=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/UncategorizedPartySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/UncategorizedParty",
  "definitions": {
    "UncategorizedParty": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "partyType",
        "uncategorizedPartyLabel",
        "id"
      ],
      "properties": {
        "partyType": {
          "type": "string"
        },
        "globalParty": {
          "type": "string"
        },
        "noMergeReason": {
          "type": "string"
        },
        "primaryAccount": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "creationReason": {
          "type": "string"
        },
        "uncategorizedPartyLabel": {
          "type": "string"
        },
        "originalSourceRecord": {
          "type": "string"
        },
        "originalSourceSystem": {
          "type": "string"
        }
      }
    }
  }
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/examples/UncategorizedPartyExample.json
{
  "partyType": "ad id",
  "uncategorizedPartyLabel": "anim sit nulla nostrud",
  "id": "commodo in aliqua",
  "originalSourceSystem": "magna",
  "globalParty": "ipsum",
  "creationReason": "labore proident id sit",
  "originalSourceRecord": "culpa Duis consectetur incididunt",
  "primaryAccount": [
    "fugiat",
    "ut incididunt non",
    "nisi",
    "ea consequat magna",
    "anim ut sint ipsum",
    "aliqua labore quis",
    "ullamco sunt quis",
    "enim in",
    "proident minim eiusmod veniam sunt"
  ],
  "noMergeReason": "laborum cillum dolor"
}

=== gvenkataramanakumar/accel-saphana-purchaseorder-sys-api/src/main/resources/api/exchange_modules/05ccff16-2d51-4e93-b543-f7e7a27faf55/cim_extended_coupa/1.0.9/examples/UncategorizedPartyDetailExample.json
{
  "partyType": "ad nulla",
  "uncategorizedPartyLabel": "ea do",
  "id": "Lorem incididunt",
  "globalParty": "eiusmod",
  "originalSourceRecord": "nostrud velit qui ad sint",
  "primaryAccount": [
    "minim ut",
    "ut ut aute",
    "qui non",
    "qui sit amet velit est",
    "nostrud Excepteur",
    "laboris ad consectetur quis",
    "esse",
    "quis laboris irure",
    "fugiat enim",
    "consectetur voluptate dolor incididunt",
    "voluptate irure amet",
    "laboris sed",
    "est cupidatat enim proident",
    "amet in culpa qui velit",
    "ipsum Lorem in ad est",
    "consectetur dolore ullamco",
    "aute qui fugiat sed",
    "cupidatat dolore Ut",
    "nulla",
    "magna esse anim minim tempor",
    "cupidatat esse non Lorem exercitation",
    "eiusmod",
    "dolore officia ullamco",
    "id cupidatat aute pariatur qui",
    "occaecat amet cupidatat elit",
    "in",
    "ipsum Duis culpa",
    "ullamco Lorem est qui",
    "aute in pariatur ipsum",
    "adipisicing sed",
    "eiusmod aliqua",
    "velit tempor aute",
    "culpa",
    "dolore fugiat in do proident",
    "officia nulla deserunt nisi",
    "in",
    "quis sed proident ipsum nostrud",
    "mollit aliquip proident ex consequat",
    "deserunt enim",
    "laborum id",
    "ut laborum pariatur sint",
    "officia",
    "pariatur",
    "laboris Lorem",
    "elit amet veniam dolor proident",
    "dolore",
    "dolor Excepteur nulla non laborum",
    "esse ipsum cupidatat",
    "anim ullamco culpa",
    "veniam",
    "eu",
    "officia in est",
    "cupidatat",
    "quis est consequat labore",
    "exercitation id eu in mollit",
    "do nostrud",
    "labore reprehenderit",
    "incididunt sint",
    "cillum esse est consectetur et",
    "deserunt in velit quis incididunt",
    "in elit aute Ut",
    "ad consectetur",
    "sed consectetur",
    "sint laborum culpa",
    "sunt exercitation sint do quis",
    "consectetur",
    "reprehenderit tempor laborum",
    "anim laboris non exercitation",
    "ea ullamco deserunt culpa",
    "in Duis amet ipsum veniam",
    "sed",
    "quis proident",
    "dolor ex ad eu",
    "mollit enim amet veniam",
    "irure cupidatat",
    "Duis officia",
    "ad",
    "proident",
    "incididunt dolor deserunt occaecat",
    "non veniam id adipisicing",
    "aliqua do",
    "aliqua mollit labore",
    "dolor est",
    "aliqua nostrud",
    "ex"
  ]
}
